window.QUIZ_BANK = {
  "easy": [
    {"q":"Where do giant pandas mostly live in the wild?","o":["Sichuan","Beijing","Xinjiang","Hainan"],"a":"Sichuan","f":"Pandas were unknown to the West until 1869.","c":"nature"},
    {"q":"What is the capital of China?","o":["Beijing","Shanghai","Guangzhou","Shenzhen"],"a":"Beijing","f":"Beijing has been China's capital for over 800 years.","c":"geo"},
    {"q":"Roughly how many people live in China?","o":["1.4 billion","500 million","2 billion","900 million"],"a":"1.4 billion","f":"That's about 1 in 6 people on Earth.","c":"geo"},
    {"q":"Which food is the staple of most Chinese meals?","o":["Rice","Bread","Potato","Pasta"],"a":"Rice","f":"China grows about 30% of the world's rice.","c":"food"},
    {"q":"Which festival is the most important in China?","o":["Lunar New Year","Halloween","Christmas","Easter"],"a":"Lunar New Year","f":"It creates the biggest annual human migration on Earth.","c":"festival"},
    {"q":"The Forbidden City is located in which city?","o":["Beijing","Nanjing","Chengdu","Hangzhou"],"a":"Beijing","f":"It has 9,999.5 rooms — 10,000 is reserved for heaven.","c":"geo"},
    {"q":"The Terracotta Warriors guard the tomb of which emperor?","o":["Qin Shi Huang","Kangxi","Wu Zetian","Qianlong"],"a":"Qin Shi Huang","f":"Each of the 8,000 warriors has a unique face.","c":"history"},
    {"q":"What do Chinese people traditionally eat with?","o":["Chopsticks","Hands","Fork","Spoon only"],"a":"Chopsticks","f":"Chopsticks are over 3,000 years old.","c":"food"},
    {"q":"What does the Chinese dragon traditionally symbolize?","o":["Good luck and power","Danger","Rain only","War"],"a":"Good luck and power","f":"Dragons are kind in Chinese myth — unlike in the West.","c":"culture"},
    {"q":"Which sport is called China's national sport?","o":["Table tennis","Football","Basketball","Badminton"],"a":"Table tennis","f":"China has won more Olympic table tennis golds than anyone.","c":"sport"},
    {"q":"Which tea is most associated with China?","o":["Green tea","Black tea","Herbal tea","Earl Grey"],"a":"Green tea","f":"Legend says tea was discovered in 2737 BC by Emperor Shennong.","c":"food"},
    {"q":"What is China's currency called?","o":["Yuan / Renminbi","Yen","Won","Taka"],"a":"Yuan / Renminbi","f":"Renminbi means the people's currency.","c":"money"},
    {"q":"How many animals are in the Chinese zodiac?","o":["12","10","24","8"],"a":"12","f":"The Jade Emperor held a race — the rat won by riding the ox.","c":"culture"},
    {"q":"What is the most famous dish from Beijing?","o":["Peking duck","Sushi","Tacos","Pizza"],"a":"Peking duck","f":"Peking duck has been roasted since imperial times.","c":"food"},
    {"q":"Which river is the longest in China?","o":["Yangtze","Yellow River","Pearl River","Mekong"],"a":"Yangtze","f":"The Yangtze is the 3rd longest river in the world.","c":"nature"},
    {"q":"What do pandas mainly eat?","o":["Bamboo","Meat","Fruit","Grass"],"a":"Bamboo","f":"They eat up to 38 kg of bamboo every day.","c":"nature"},
    {"q":"Which city has the Oriental Pearl Tower?","o":["Shanghai","Beijing","Shenzhen","Xi'an"],"a":"Shanghai","f":"Shanghai's skyline was built in just 30 years.","c":"geo"},
    {"q":"What does China's national flag look like?","o":["Red with yellow stars","Blue with white stars","All green","Black and white"],"a":"Red with yellow stars","f":"Red symbolizes revolution; the big star is the Party.","c":"culture"},
    {"q":"What is Mount Everest called in China?","o":["Qomolangma","K2","Kilimanjaro","Fuji"],"a":"Qomolangma","f":"Qomolangma means Goddess Mother in Tibetan.","c":"nature"},
    {"q":"Who is the legendary kung fu star who made it global?","o":["Bruce Lee","Chuck Norris","Steven Seagal","Tony Jaa"],"a":"Bruce Lee","f":"Bruce Lee made the word kung fu famous worldwide.","c":"people"},
    {"q":"Which animal brings luck in Chinese New Year paintings?","o":["Carp","Owl","Cat","Wolf"],"a":"Carp","f":"A carp that jumps the dragon gate turns into a dragon.","c":"culture"},
    {"q":"Hotpot (huoguo) from Sichuan is famous for being...","o":["Spicy","Sweet","Sour","Tasteless"],"a":"Spicy","f":"The numbing spice is called mala — numbing and hot.","c":"food"},
    {"q":"What is the most common noodle in China made from?","o":["Wheat","Soba","Udon","Spaghetti"],"a":"Wheat","f":"Long noodles mean long life — never cut them!","c":"food"},
    {"q":"What was Xi'an (Chang'an) famous for?","o":["Start of the Silk Road","End of the Great Wall","Tea capital","Fishing port"],"a":"Start of the Silk Road","f":"Chang'an was the Silk Road's eastern starting point.","c":"history"},
    {"q":"Which Chinese city has the largest population?","o":["Shanghai","Lhasa","Hohhot","Yinchuan"],"a":"Shanghai","f":"Around 25 million people call Shanghai home.","c":"geo"},
    {"q":"What does China have the most of in the world?","o":["High-speed rail","Airports","Deserts","Castles"],"a":"High-speed rail","f":"China's HSR network is longer than the rest of the world combined.","c":"tech"},
    {"q":"How do most Chinese people pay in shops today?","o":["Phone QR codes","Cash only","Credit cards only","Barter"],"a":"Phone QR codes","f":"Even street vendors take WeChat and Alipay QR payments.","c":"tech"},
    {"q":"What animal dance is a Lunar New Year highlight?","o":["Dragon dance","Elephant dance","Camel dance","Shark dance"],"a":"Dragon dance","f":"Lion and dragon dances chase away evil spirits.","c":"festival"},
    {"q":"What round dessert is eaten at Mid-Autumn Festival?","o":["Mooncake","Cheesecake","Tiramisu","Donut"],"a":"Mooncake","f":"Its round shape means family reunion under the full moon.","c":"food"},
    {"q":"Dumplings (jiaozi) are traditionally eaten at...","o":["New Year","Christmas","Halloween","Easter"],"a":"New Year","f":"They look like ancient gold ingots — money!","c":"food"}
  ],
  "medium": [
    {"q":"The Grand Canal connects Beijing with which region?","o":["Hangzhou","Tibet","Xinjiang","Hainan"],"a":"Hangzhou","f":"It is the world's longest artificial waterway: 1,776 km.","c":"history"},
    {"q":"The Silk Road mainly linked China with...","o":["Europe","Australia","America","Antarctica"],"a":"Europe","f":"Silk, tea and porcelain traveled west for 1,500 years.","c":"history"},
    {"q":"The Mogao Caves are in which province?","o":["Gansu","Guangdong","Fujian","Jilin"],"a":"Gansu","f":"They hold 2,000+ years of Buddhist art in Dunhuang.","c":"culture"},
    {"q":"Guilin is famous for which type of landscape?","o":["Karst peaks","Desert dunes","Volcanoes","Glaciers"],"a":"Karst peaks","f":"The Li River cruise is the classic way to see them.","c":"nature"},
    {"q":"Huangshan (Yellow Mountain) is famous for its...","o":["Pines and sea of clouds","Snowboarding","Beaches","Waterfalls only"],"a":"Pines and sea of clouds","f":"Its four wonders include hot springs and odd rocks.","c":"nature"},
    {"q":"Suzhou is famous for which type of garden?","o":["Classical gardens","Botanical","Tropical","Zen sand"],"a":"Classical gardens","f":"They imitate nature in miniature — walking in a painting.","c":"culture"},
    {"q":"In Peking Opera, what does a red face mean?","o":["Brave and loyal","Evil","Ghost","Poor"],"a":"Brave and loyal","f":"Black means rough and fair; white means cunning.","c":"culture"},
    {"q":"What is the traditional Chinese dress called?","o":["Cheongsam (qipao)","Kimono","Ao dai","Sari"],"a":"Cheongsam (qipao)","f":"It went from Manchu court fashion to a global icon.","c":"culture"},
    {"q":"Which of these is one of China's Four Great Inventions?","o":["Compass","Steam engine","Electricity","Internet"],"a":"Compass","f":"The other three: paper, printing and gunpowder.","c":"tech"},
    {"q":"Dragon Boat Festival honors which ancient poet?","o":["Qu Yuan","Li Bai","Du Fu","Confucius"],"a":"Qu Yuan","f":"Zongzi were thrown in rivers to feed fish instead of him.","c":"festival"},
    {"q":"West Lake is in which city?","o":["Hangzhou","Suzhou","Nanjing","Wuhan"],"a":"Hangzhou","f":"Its ten scenic views inspired poets for 1,000 years.","c":"geo"},
    {"q":"Zhangjiajie inspired the floating mountains of which movie?","o":["Avatar","Titanic","Inception","Frozen"],"a":"Avatar","f":"Its quartz pillars rise over 300 m above the forest.","c":"nature"},
    {"q":"The Potala Palace sits in which city?","o":["Lhasa","Chengdu","Xining","Kashgar"],"a":"Lhasa","f":"It was the Dalai Lama's winter palace since 1649.","c":"geo"},
    {"q":"Which town is a famous canal water town?","o":["Wuzhen","Zhangjiajie","Datong","Kashgar"],"a":"Wuzhen","f":"Its gondola rides rival Venice at a fraction of the price.","c":"geo"},
    {"q":"The tallest of China's Five Sacred Mountains is...","o":["Hua Shan","Tai Shan","Heng Shan","Song Shan"],"a":"Hua Shan","f":"Its plank walk is one of the world's scariest trails.","c":"nature"},
    {"q":"The world's largest stone Buddha sits in...","o":["Leshan","Shanghai","Macao","Harbin"],"a":"Leshan","f":"At 71 m tall, a family could sit on each of its toes.","c":"culture"},
    {"q":"Which city is known as the Porcelain Capital?","o":["Jingdezhen","Chongqing","Shenyang","Nanning"],"a":"Jingdezhen","f":"Its imperial kilns made porcelain for 1,000 years.","c":"culture"},
    {"q":"The Three Gorges Dam is on which river?","o":["Yangtze","Yellow River","Pearl River","Songhua"],"a":"Yangtze","f":"It is the world's largest power station by capacity.","c":"tech"},
    {"q":"Harbin's winter festival is famous for...","o":["Ice and snow sculptures","Ski resorts","Hot springs","Polar bears"],"a":"Ice and snow sculptures","f":"The ice city covers 1.2 million square meters of frozen art.","c":"festival"},
    {"q":"How many ethnic groups officially live in China?","o":["56","12","99","8"],"a":"56","f":"Han is about 91%; Zhuang is the largest minority.","c":"culture"},
    {"q":"The Water-Splashing Festival belongs to which group?","o":["Dai","Mongolian","Tibetan","Uyghur"],"a":"Dai","f":"Splashing water washes away bad luck for their New Year.","c":"festival"},
    {"q":"Naadam (wrestling, archery, horse racing) is whose festival?","o":["Mongolian","Han","Hui","Korean"],"a":"Mongolian","f":"It happens every July on the grasslands.","c":"festival"},
    {"q":"Jiaozi dumplings look like which lucky object?","o":["Gold ingots","Flowers","Stars","Keys"],"a":"Gold ingots","f":"Eating them at midnight means wealth for the new year.","c":"food"},
    {"q":"Long noodles at a birthday celebration mean...","o":["Long life","Good grades","Fast travel","Strong muscles"],"a":"Long life","f":"Slurping is polite — cutting them is bad luck.","c":"food"},
    {"q":"Why is the number 8 lucky in China?","o":["Sounds like prosper","Looks like a dragon","Emperor's number","Means infinity"],"a":"Sounds like prosper","f":"Phone numbers full of 8s have sold for millions.","c":"culture"},
    {"q":"Which number sounds like death in Chinese?","o":["4","9","2","6"],"a":"4","f":"Some buildings skip floor 4 like the West skips 13.","c":"culture"},
    {"q":"In your zodiac birth year (benmingnian) you should wear...","o":["Red","White","Black","Green"],"a":"Red","f":"Red scares away bad luck and the year beast.","c":"culture"},
    {"q":"What does 520 mean in Chinese internet slang?","o":["I love you","Goodbye","Happy birthday","Get rich"],"a":"I love you","f":"Wu er ling sounds like wo ai ni — I love you.","c":"culture"},
    {"q":"Which app do Chinese use to book high-speed train tickets?","o":["12306","TripAdvisor","Airbnb","Booking.com"],"a":"12306","f":"During Spring Festival it sells about 20 million tickets a day.","c":"tech"},
    {"q":"How many players does mahjong traditionally need?","o":["4","2","6","8"],"a":"4","f":"It mixes skill, luck and strategy — over 100 years old.","c":"culture"},
    {"q":"Tai chi is best known as...","o":["A slow-motion martial art","A cooking style","A musical instrument","A dance party"],"a":"A slow-motion martial art","f":"Every dawn, millions practice it in parks.","c":"sport"},
    {"q":"The Temple of Heaven was built for...","o":["Emperors praying for harvests","War strategy","Astronomers","Trading"],"a":"Emperors praying for harvests","f":"The emperor stood at its center as the Son of Heaven.","c":"history"},
    {"q":"Kung fu tea is famous in which region?","o":["Guangdong and Chaozhou","Heilongjiang","Xinjiang","Qinghai"],"a":"Guangdong and Chaozhou","f":"The ritual can take minutes to pour one tiny cup.","c":"food"},
    {"q":"Which animal is NOT in the Chinese zodiac?","o":["Cat","Rat","Tiger","Rabbit"],"a":"Cat","f":"Legend says the rat tricked the cat and made it miss the race.","c":"culture"},
    {"q":"Bianlian (face changing) belongs to which opera?","o":["Sichuan opera","Peking opera","Cantonese opera","Kunqu"],"a":"Sichuan opera","f":"Masters change masks faster than the eye can see.","c":"culture"},
    {"q":"Shadow puppetry (piying) is traditionally made from...","o":["Leather","Glass","Paper only","Wood"],"a":"Leather","f":"UNESCO listed it as intangible heritage in 2011.","c":"culture"},
    {"q":"Chinese paper cutting is traditionally used for...","o":["Window decorations","Money","Wrapping gifts","Bookmarks"],"a":"Window decorations","f":"Red cutouts at New Year mean double happiness.","c":"culture"},
    {"q":"Tangyuan (rice balls) are eaten at which festival?","o":["Lantern Festival","Qingming","Mid-Autumn","Double Ninth"],"a":"Lantern Festival","f":"Round means reunion; sweet means a sweet life.","c":"food"},
    {"q":"Which ancient city was the eastern start of the Silk Road?","o":["Xi'an","Shanghai","Guangzhou","Harbin"],"a":"Xi'an","f":"Then called Chang'an, it was the world's largest city in 700 AD.","c":"history"},
    {"q":"What is the Beijing Central Axis?","o":["A 7.8 km line of landmarks","A metro line","A river","A mountain range"],"a":"A 7.8 km line of landmarks","f":"UNESCO-listed in 2024: gates, altars and the Forbidden City.","c":"geo"}
  ],
  "hard": [
    {"q":"Officially, how many rooms does the Forbidden City have?","o":["9,999.5","10,000","888","365"],"a":"9,999.5","f":"Only heaven gets the mythical 10,000.","c":"history"},
    {"q":"What is China's earliest known writing?","o":["Oracle bones","Papyrus","Cuneiform","Runes"],"a":"Oracle bones","f":"Shang dynasty turtle shells (1200 BC) asked questions of gods.","c":"history"},
    {"q":"The Tea Horse Road linked Yunnan with...","o":["Tibet","Korea","Vietnam","Mongolia"],"a":"Tibet","f":"Tea went up; horses came down — over 4,000 km of mountain trails.","c":"history"},
    {"q":"Which is the lowest point in China?","o":["Aydingkol Lake","Taklamakan","Qinghai Lake","Karakoram"],"a":"Aydingkol Lake","f":"Near Turpan, it lies 154 m below sea level.","c":"nature"},
    {"q":"The world's highest bridge (by deck height) is...","o":["Beipanjiang Bridge","Golden Gate","Millau","Sydney Harbour"],"a":"Beipanjiang Bridge","f":"Its deck hangs 565 m above the valley floor.","c":"tech"},
    {"q":"Which Hakka fortress type is UNESCO-listed?","o":["Tulou","Hutong","Siheyuan","Yaodong"],"a":"Tulou","f":"Round earth buildings housed whole clans — up to 1,000 people.","c":"culture"},
    {"q":"Which dynasty built the Great Wall sections most tourists see?","o":["Ming","Qin","Han","Tang"],"a":"Ming","f":"The Qin first emperor's wall ran north of today's ruins.","c":"history"},
    {"q":"The Yangtze River is the ___ longest river in the world.","o":["3rd","1st","5th","10th"],"a":"3rd","f":"It runs 6,300 km from Qinghai-Tibet to Shanghai.","c":"nature"},
    {"q":"What is the Taklamakan Desert nicknamed?","o":["Sea of Death","Sea of Sand","Golden Desert","White Sea"],"a":"Sea of Death","f":"Its Uyghur name means you go in, you don't come out.","c":"nature"},
    {"q":"Which of China's Four Great Inventions came earliest?","o":["Compass","Paper","Gunpowder","Printing"],"a":"Compass","f":"Early compasses were lodestone spoons from 4th century BC.","c":"tech"},
    {"q":"Zongzi are wrapped in which leaves?","o":["Bamboo","Banana","Lotus","Maple"],"a":"Bamboo","f":"The pyramid shape has survived 2,000 years.","c":"food"},
    {"q":"Dim sum literally means...","o":["Touch the heart","Small plate","Morning tea","Cantonese bite"],"a":"Touch the heart","f":"It started as teahouse snacks along the Silk Road.","c":"food"},
    {"q":"The highest railway station in the world is at...","o":["Tanggula (Tibet)","Lhasa","Chengdu","Kunming"],"a":"Tanggula (Tibet)","f":"It sits 5,068 m above sea level on the Lhasa railway.","c":"tech"},
    {"q":"How many Chinese characters do you need for basic reading?","o":["About 3,000","50,000","100","50"],"a":"About 3,000","f":"But dictionaries list 50,000+; the biggest has over 100,000.","c":"culture"},
    {"q":"What color dominates Chinese weddings?","o":["Red","White","Blue","Purple"],"a":"Red","f":"The double happiness symbol means double joy.","c":"culture"},
    {"q":"Xiehouyu is...","o":["A two-part witty saying","A dance","A noodle dish","A dynasty"],"a":"A two-part witty saying","f":"Example: mute eating dumplings — knows how many in the heart.","c":"culture"},
    {"q":"The Great Wall Marathon runs on which section?","o":["Huangyaguan","Badaling","Mutianyu","Jinshanling"],"a":"Huangyaguan","f":"Runners climb 5,164 stone steps along the wall.","c":"sport"},
    {"q":"Hot dry noodles (reganmian) are the breakfast of which city?","o":["Wuhan","Chengdu","Xi'an","Harbin"],"a":"Wuhan","f":"Wuhan students joke they miss reganmian more than home.","c":"food"},
    {"q":"Which opera form uses face-changing masks?","o":["Sichuan opera","Peking opera","Cantonese opera","Kunqu"],"a":"Sichuan opera","f":"Bianlian masters switch masks in about 0.3 seconds.","c":"culture"},
    {"q":"Suzhou is historically the city of...","o":["Silk","Porcelain","Jade","Salt"],"a":"Silk","f":"Its silk reached the Roman Empire via the Silk Road.","c":"culture"},
    {"q":"Original Chongqing hotpot starred which cheap ingredient?","o":["Beef tripe","Chicken breast","Lobster","Tofu only"],"a":"Beef tripe","f":"Boatmen invented it, boiling cheap scraps in spicy broth.","c":"food"},
    {"q":"The Ten Views of West Lake are...","o":["Named scenic spots","A painting style","Poems only","Tea names"],"a":"Named scenic spots","f":"One is called Remnant Snow on Broken Bridge.","c":"culture"},
    {"q":"Which mountain hosts the Shaolin Temple?","o":["Songshan","Huashan","Taishan","Emeishan"],"a":"Songshan","f":"Kung fu's most famous home — all martial arts under heaven.","c":"culture"},
    {"q":"Chinese chess (xiangqi) differs from chess because it has...","o":["A river and cannons","Queens","No kings","Blind play"],"a":"A river and cannons","f":"The board has a river dividing the two armies.","c":"culture"},
    {"q":"Which dynasty ruled Yuan China?","o":["Mongol","Han","Manchu","Tibetan"],"a":"Mongol","f":"Kublai Khan's court amazed Marco Polo.","c":"history"},
    {"q":"What is the highest mountain located in China proper?","o":["Qomolangma (Everest)","K2","Gongga","Jade Dragon"],"a":"Qomolangma (Everest)","f":"It stands 8,848.86 m, shared with Nepal.","c":"nature"},
    {"q":"Mamahuhu literally means horse horse tiger tiger — but actually...","o":["So-so","Very happy","Run away","Horse festival"],"a":"So-so","f":"It describes careless, not-great, middle-quality work.","c":"culture"},
    {"q":"Roujiamo (the Chinese burger) is the street food of which city?","o":["Xi'an","Shanghai","Guangzhou","Dalian"],"a":"Xi'an","f":"Called China's oldest hamburger — 2,000+ years.","c":"food"},
    {"q":"The Bird's Nest hosted the Olympics in which year?","o":["2008","2012","2004","2022"],"a":"2008","f":"The 2022 Winter Games reused the same stadium.","c":"sport"},
    {"q":"What does the Great Wall's total length officially measure?","o":["21,196 km","5,000 km","10,000 km","3,000 km"],"a":"21,196 km","f":"That includes all branches — a full survey finished in 2012.","c":"history"}
  ]
};
