import os
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""City data batch B: kashgar, lijiang, ordos, pingwu-baima, changxing, hengqin, yiwu, zhangjiajie."""

CITIES = []

# ============================================================ KASHGAR
CITIES.append({
  "file": "kashgar.html",
  "title": "Kashgar Travel Guide — Ready? China!",
  "meta": "The honest guide to Kashgar for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "喀什古城", "en": "Kashgar", "emoji": "🏛️",
  "sub": "Uyghur craft bazaar, Silk Road living museum",
  "meta_tags": ["★★★★★", "🗓 2–3 days", "Silk Road bazaar", "Ethnic culture", "Off the beaten path"],
  "hero_bg": "",
  "hero_grad": "linear-gradient(135deg, #5a3a2a 0%, #a06a3a 100%)",
  "why_emoji": "🏛️",
  "why": [
    "Kashgar is the farthest west you can go in China — a Silk Road city on the edge of the Taklamakan Desert where Uyghur culture, Central Asian bazaars and 2,000 years of trade history still fill the streets. It's the most different place in China from anything you've seen: adobe alleyways, mosques, melons piled high, and a Sunday livestock market that hasn't changed in centuries.",
    "This is ★★★★★ difficulty — very little English, an overnight flight from the east, and a culture that rewards patience. But for travelers who make it, Kashgar is the single most memorable stop in the country: a living Silk Road museum that feels a world away from Beijing or Shanghai."
  ],
  "top5": [
    {"id":"old-city", "title":"Kashgar Old City", "tag":"A 2,000-year-old adobe maze", "ph_emoji":"🏘",
     "img":"",
     "story":"The old city of Kashgar has stood for over 2,000 years as a trading post on the Silk Road, its maze of adobe alleyways and wooden balconies barely changed since the days when caravans rested here between China and Central Asia. Today some 70,000 people live inside its walls, in homes built like a honeycomb — flat-roofed, mud-brick, and connected by lanes so narrow that two people can barely pass.",
     "why":"This is not a museum or a film set — it's a living neighborhood where children play in the alleys, craftsmen hammer copper in their doorways, and the smell of naan bread fills the air. Wandering without a plan is the whole point; every turn reveals a workshop, a courtyard, or a group of elders playing chess under a grape trellis.",
     "tip":"Enter through the East Gate (the grand opening ceremony happens at 10am) and just walk. Greet people with 'salam' and a smile — locals are famously warm. Allow a full half day; the alleys are endless."},
    {"id":"id-kah", "title":"Id Kah Mosque &amp; the Sunday livestock market", "tag":"The heart of Uyghur Kashgar", "ph_emoji":"🕌",
     "img":"",
     "story":"Id Kah Mosque, founded in 1442 and enlarged over centuries, is the largest mosque in China — its courtyard can hold over 20,000 worshippers for Friday prayers. On Sundays, the square around it and the nearby livestock market fill with farmers selling sheep, donkeys, horses and camels in a scene that looks straight out of the 19th century.",
     "why":"The Sunday livestock market is one of the great street spectacles of Asia: thousands of animals, traders slapping hands to seal deals, and food stalls cooking the morning's catch. And the mosque — with its yellow-tiled gateway and vast courtyard — is the architectural heart of Uyghur Kashgar.",
     "tip":"The livestock market peaks before 10am on Sundays — go early, it's at the town's west edge (taxi ~15 RMB). The mosque is open to visitors outside prayer times (entry 30 RMB); dress modestly."},
    {"id":"handicraft-street", "title":"Handicraft Street", "tag":"Copper, carpets &amp; centuries-old crafts", "ph_emoji":"⚒️",
     "img":"",
     "story":"Kashgar's craft quarter is a street-long workshop where Uyghur artisans practice trades their families have held for generations: hammering copper pots, weaving carpets, forging knives, embroidering hats and carving wooden instruments. Many workshops have been here since before the Silk Road caravans stopped using camels.",
     "why":"You can watch a copper pot being born from a flat sheet of metal, smell the wool of fresh carpets, and buy directly from the makers — no middlemen, no factory replicas. It's the closest thing left to a genuine Silk Road bazaar, and the craftsmanship is extraordinary.",
     "tip":"Bargain politely but fairly — these are working artisans, and the quality justifies the price. Copper teapots (~100–300 RMB) and embroidered caps (~30–80 RMB) make the best gifts. Ask before photographing the craftsmen."},
    {"id":"naan", "title":"Fresh naan &amp; a Uyghur tea house", "tag":"The best bread on the Silk Road", "ph_emoji":"🥖",
     "img":"",
     "story":"Naan — flatbread baked on the walls of a clay oven — is the staff of life in Kashgar, and every neighborhood has its bakery. The classic round naan is stamped with a pattern, brushed with sesame and baked in seconds at 300°C. Karim's Bakery in the old city is locally famous for the freshest loaves; pair one with salted milk tea or a Uyghur fruit-and-nut tea in a traditional tea house.",
     "why":"There's nothing like naan straight from a clay oven at 7am in an adobe alley — crisp-edged, chewy-centered, dusted with sesame. And the tea houses of the old city, where men gather all day over melon seeds and endless refills of tea, are the social heart of Kashgar.",
     "tip":"Naan costs 3–5 RMB — buy a few for the day. For the tea-house scene, look for one with carpets on the platforms and locals playing dap (drum); the Uyghur tea with almonds, raisins and rock sugar is the classic order."},
    {"id":"street-food", "title":"Lamb kebabs &amp; hand-pulled noodles", "tag":"Silk Road food, grilled over charcoal", "ph_emoji":"🍢",
     "img":"",
     "story":"Kashgar's food is Central Asian to the core: lamb kebabs grilled over charcoal with cumin and chili, hand-pulled noodles (laghman) tossed with lamb and peppers, polo (pilaf) cooked with carrots and raisins, and grilled whole fish from nearby rivers. This is the food the Silk Road traded — and it's still cooked the same way.",
     "why":"After weeks of Chinese food, Kashgar's meat-and-noodle cooking hits completely differently: smoky kebabs, fragrant pilaf, and the best bread in Asia. The night market near the old city's east gate is the place to graze from stall to stall.",
     "tip":"Kebab stalls with long queues are the good ones — order 10 skewers and stand there eating them. Try polo (5–15 RMB) and laghman (10–20 RMB) from the old-city kitchens. Finish with a bowl of local yogurt."}
  ],
  "stay": [
    {"name":"Inside the Old City", "badge":"Immersive experience",
     "desc":"Boutique guesthouses tucked into the adobe lanes — Uyghur courtyard houses with carved wooden balconies, where you wake up to the call to prayer and the sound of naan baking. The most atmospheric stay in China, full stop.",
     "metro":"No metro — old city is walkable; taxis cheap", "landmark":"Old City East Gate, Handicraft Street",
     "hotel":"e.g. Kashgar Old City boutique guesthouses (traditional Uyghur courtyards) · from ~250 RMB"},
    {"name":"City center (People's Square)", "badge":"Comfort &amp; convenience",
     "desc":"The modern center around People's Square and the Id Kah area: international-standard hotels, English-speaking staff at the better ones, and easy taxi access to the old city (10 minutes). Best choice if you want comfort after intense days.",
     "metro":"No metro — taxis across town ~10–20 RMB", "landmark":"Id Kah Mosque, People's Square, night market",
     "hotel":"e.g. Radisson Blu Kashgar (international comfort) · local 3–4 star hotels"},
    {"name":"Seminary / old city west edge", "badge":"Budget &amp; backpackers",
     "desc":"A cluster of budget hostels and guesthouses around the old city's western lanes — atmospheric, central and cheap. Shared bathrooms at the cheapest places, but you're right in the action.",
     "metro":"No metro — walk to the old city", "landmark":"Seminary area, old city west gates, bazaar",
     "hotel":"e.g. Seminary Hostel (converted madrasa, atmospheric) · budget guesthouses from ~100 RMB"}
  ],
  "eat": [
    {"name":"Lamb Kebabs", "zh":"烤肉", "ph_emoji":"🍢",
     "img":"",
     "desc":"Chargrilled over charcoal with cumin and chili — you'll smell them three blocks away. The definitive Kashgar street food, eaten standing up.",
     "where":"🍽 Night market &amp; old city stalls · ¥3–5 per skewer"},
    {"name":"Hand-Pulled Noodles (Laghman)", "zh":"拉条子", "ph_emoji":"🍜",
     "img":"",
     "desc":"Thick, chewy noodles hand-ripped and tossed with lamb, peppers and tomatoes ��� a Uyghur staple you'll dream about after you leave.",
     "where":"🍽 Old city noodle kitchens · ¥10–20"},
    {"name":"Polo (Pilaf)", "zh":"抓饭", "ph_emoji":"🍛",
     "img":"",
     "desc":"Fragrant rice slow-cooked with lamb, carrots and raisins — Central Asia on a plate. Often topped with a piece of melt-tender lamb.",
     "where":"🍽 Polo houses near the bazaar · ¥10–25"},
    {"name":"Naan &amp; Salted Milk Tea", "zh":"馕与奶茶", "ph_emoji":"🥖",
     "img":"",
     "desc":"Fresh clay-oven naan dipped in salty, buttery milk tea — the breakfast (and lunch, and snack) of the Silk Road.",
     "where":"🍽 Karim's Bakery &amp; old city tea houses · ¥3–10"}
  ],
  "tips": [
    "Kashgar is ★★★★★ difficulty: English is rare, Uyghur and Mandarin dominate. Download Pleco + an offline translation app before you go, and learn 'salam' (hello) and 'rahmat' (thanks).",
    "Bring cash! Many old-city shops and stalls don't accept cards or foreign WeChat Pay — RMB cash is still king in the bazaar.",
    "The Sunday livestock market is the single greatest street spectacle in China — go before 10am. And fly in/out (5+ hour flights); there's no easy train from the east.",
  ],
  "related": [
    {"file":"xian.html", "zh":"西安", "en":"Xi'an", "emoji":"🏺", "desc":"Ancient history, Terracotta Army, Silk Road",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460318/terracotta-army_pp8yhk.jpg"},
    {"file":"dunhuang.html", "zh":"敦煌", "en":"Dunhuang", "emoji":"🕌", "desc":"Mogao Caves, desert landscapes, Silk Road art",
     "grad":"background:linear-gradient(135deg,#7a5a2a,#c9a05a)"},
  ],
})

# ============================================================ LIJIANG
CITIES.append({
  "file": "lijiang.html",
  "title": "Lijiang Travel Guide — Ready? China!",
  "meta": "The honest guide to Lijiang for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "丽江", "en": "Lijiang", "emoji": "🏔️",
  "sub": "Naxi culture, cobblestone old town, Jade Dragon Snow Mountain",
  "meta_tags": ["★★★☆☆", "🗓 2–3 days", "Old town charm", "Nightlife", "Snow mountain"],
  "hero_bg": "",
  "hero_grad": "linear-gradient(135deg, #2a3a5a 0%, #5a7a9a 100%)",
  "why_emoji": "🏔️",
  "why": [
    "Lijiang is where China's old town charm meets its highest drama: a 800-year-old cobblestone town of canals and wooden houses (UNESCO World Heritage since 1997), set against the 5,596-meter Jade Dragon Snow Mountain rising right behind it. It's the home of the Naxi people and their Dongba culture — the last living pictographic script on earth.",
    "By day you can ride a cable car to 4,506 meters and stand on a glacier; by night the old town's bars and bonfires take over. It's the perfect blend of culture, mountain adventure and nightlife — and one of the most photographed corners of China."
  ],
  "top5": [
    {"id":"old-town", "title":"Lijiang Old Town", "tag":"An 800-year-old cobblestone maze", "ph_emoji":"🏘",
     "img":"",
     "story":"Lijiang Old Town was founded in the late Song dynasty (13th century) and built without walls — a Naxi tradition, since a city with walls 'traps' good fortune. Its cobblestone lanes follow the canals of the Jade River, which flows through every street (the Naxi used to wash the town's stone by opening sluice gates). It became a UNESCO World Heritage Site in 1997, the first old town in China to be listed.",
     "why":"There's no other old town quite like it: waterways threading every lane, stone bridges every few dozen meters, and a layout designed to be walked without ever feeling lost. It's also genuinely alive — residents still live and trade here, and the surrounding Naxi courtyards (with their 'three rooms one screen wall' architecture) are beautiful.",
     "tip":"Wander off the main tourist lanes (Sifang Street) into the quieter northern alleys, especially at 7am when the town is empty and the canals sing. Entry is free, but there's a 50 RMB 'maintenance fee' collected at some gates — it's included if you stay in a licensed guesthouse."},
    {"id":"jade-dragon", "title":"Jade Dragon Snow Mountain", "tag":"Cable car to 4,506 meters", "ph_emoji":"⛰️",
     "img":"",
     "story":"Jade Dragon Snow Mountain (Yulong Xueshan) is a 13-peak range whose highest summit reaches 5,596 meters, permanently snow-capped and towering 4,000 meters above Lijiang's valley floor. The Glacier Park cable car climbs to 4,506 meters — among the highest cable car stations in Asia — putting you on a real glacier at the edge of the clouds.",
     "why":"The contrast is the magic: subtropical valley one moment, glacier and thin air the next. The ride up is a show of its own, and at the top you can walk a boardwalk onto the glacier itself. Below, the Impression Lijiang show (by the director of Avatar's sound designer, Zhang Yimou's team) sets 500 performers against the mountain.",
     "tip":"Book the cable car ticket online (peak season sells out days ahead; ~140 RMB + entrance 100 RMB). Bring oxygen (30 RMB at the base) even if you feel fine — altitude hits fast. Go early; clouds roll in by noon."},
    {"id":"black-dragon-pool", "title":"Black Dragon Pool", "tag":"The classic reflection of the snow mountain", "ph_emoji":"🌊",
     "img":"",
     "story":"Black Dragon Pool (Heilongtan) is a spring-fed lake at the north edge of the old town, designed as a Ming-dynasty park with the Jade Dragon Snow Mountain as its backdrop. The five-arch Jade Dragon Bridge and the Deyue Tower pagoda sit in the middle of the pool, and on clear days the entire snow mountain range is reflected in the still water — the most photographed view in Yunnan.",
     "why":"It's the postcard shot: pagoda, bridge and snow mountain in a single frame of mirror-still water. The park is also home to the Dongba Museum, where you can see the Naxi's pictographic script — the world's last living pictographic writing system — up close.",
     "tip":"Go in the early morning for the calmest water and the clearest reflection; by 10am the wind picks up and the mirror ripples. Entry 50 RMB (some hotels include it). The Dongba Museum inside is worth 30 minutes."},
    {"id":"dongba-culture", "title":"Naxi Dongba culture show", "tag":"A 1,000-year-old pictographic script", "ph_emoji":"📜",
     "img":"",
     "story":"The Naxi people's Dongba culture is one of the world's great survivals: a religion and script — over 1,400 pictographic characters — that has been passed down by Dongba priests for over 1,000 years and is still in use today. The Dongba Culture Research Institute in Lijiang preserves it, and cultural shows around the old town stage the songs, dances and rituals that go with it.",
     "why":"You can watch an actual living pictographic script being read, and see ritual dance and music that descend from shamanic traditions older than the town itself. It's a rare chance to meet a culture that has no equivalent anywhere else on earth.",
     "tip":"Visit the Dongba Museum at Black Dragon Pool first (free with the 50 RMB park entry), then catch an evening Naxi music and dance show in the old town (from ~100 RMB). The ancient music ensemble — with 500-year-old instruments — is the unmissable one."},
    {"id":"bar-street", "title":"Old town bar street at night", "tag":"Live music, bonfires &amp; dancing", "ph_emoji":"🎸",
     "img":"",
     "story":"When the sun sets, the old town's riverside lanes turn into Yunnan's most famous nightlife strip: bars with live bands playing everything from folk to rock, bonfires where locals and travelers join hands to dance, and the canal reflections doubling every light. The main 'Bar Street' along the river is the energetic core; the side lanes hide quieter, cooler spots.",
     "why":"It's the yin to the mountain's yang: after a day of glaciers and temples, Lijiang lets loose. The bonfire circle dances (everyone holding hands, stepping in a circle to Naxi music) are joyful and unpretentious — you'll be pulled in whether you like it or not.",
     "tip":"Drinks cost double on the main Bar Street — follow the music into the side lanes for the same scene at half the price. The bonfire dance starts around 8:30pm in the main square. Be careful with the cobblestones after a couple of drinks!"}
  ],
  "stay": [
    {"name":"Inside the Old Town", "badge":"Atmosphere &amp; romance",
     "desc":"Stay in a restored Naxi courtyard house — wooden balconies, fish ponds and moon gates — right in the cobblestone maze. Magical at night when the crowds thin, but pack light: luggage has to be carried over cobblestones (some guesthouses offer pickup).",
     "metro":"No metro — walk or taxi to the old town edge", "landmark":"Sifang Street, canals, Bar Street",
     "hotel":"e.g. Blossom Hill Lijiang (boutique courtyard) · hundreds of courtyard guesthouses from ¥200"},
    {"name":"Shuhe Ancient Town", "badge":"Quieter &amp; more authentic",
     "desc":"A smaller, quieter old town 20 minutes north of Lijiang — the same cobblestone-and-canal charm without the crowds, plus better-value guesthouses. Perfect for travelers who want the old-town experience without the party.",
     "metro":"No metro — bus or taxi from Lijiang (20 min)", "landmark":"Shuhe old town, Green Dragon Bridge, Jade Dragon views",
     "hotel":"e.g. boutique courtyard hotels in Shuhe from ¥250"},
    {"name":"New town (around the old town)", "badge":"Convenience &amp; budget",
     "desc":"The modern city ring around the old town: standard hotels, easy luggage access and cheaper prices, 10 minutes' walk from the old town gates. Best if you're on a budget or arriving by plane with big bags.",
     "metro":"No metro — walking distance to old town", "landmark":"Old town gates, bus station, restaurants",
     "hotel":"e.g. InterContinental Lijiang (luxury at the mountain foot) · budget chains in the new town"},
    {"name":"Ganhaizi / Jade Dragon foothills", "badge":"Mountain views",
     "desc":"Hotels and resorts on the meadow at the foot of Jade Dragon Snow Mountain — waking up to the full mountain wall outside your window. 30 minutes from the old town; you'll taxi for meals and nightlife.",
     "metro":"No metro — taxi to old town ~30 min", "landmark":"Jade Dragon Snow Mountain, Impression Lijiang show",
     "hotel":"e.g. Banyan Tree Lijiang (mountain-view villas, splurge)"}
  ],
  "eat": [
    {"name":"Crossing-the-Bridge Noodles", "zh":"过桥米线", "ph_emoji":"🍜",
     "img":"",
     "desc":"Yunnan's most famous dish: a bowl of boiling-hot broth you cook raw toppings in at the table — sliced meat, vegetables, quail egg, and rice noodles. Named for the legend of a wife crossing a bridge to deliver it to her husband.",
     "where":"🍽 Old town noodle houses · ¥30–60 per set"},
    {"name":"Naxi Baba", "zh":"纳西粑粑", "ph_emoji":"🥞",
     "img":"",
     "desc":"Pan-fried flatbread — sweet (with sugar and nuts) or savory (with ham and scallion) — the classic Naxi street snack, crisp on the outside, soft within.",
     "where":"🍽 Street stalls across the old town · ¥10–15"},
    {"name":"Yak Meat Hotpot", "zh":"牦牛肉火锅", "ph_emoji":"🍲",
     "img":"",
     "desc":"Tender highland yak slices simmered in a spicy broth with mushrooms and greens — hearty, warming, and perfect after a cold mountain day.",
     "where":"🍽 Old town hotpot restaurants · ¥80–120 pp"},
    {"name":"Lijiang Mushroom Hotpot", "zh":"野生菌火锅", "ph_emoji":"🍄",
     "img":"",
     "desc":"Yunnan is China's mushroom kingdom — a hotpot of foraged wild mushrooms (porcini, matsutake and more) in chicken broth. Seasonal (June–Oct) and unforgettable.",
     "where":"🍽 Mushroom restaurants in the old town · ¥100–150 pp"}
  ],
  "tips": [
    "Lijiang sits at 2,400m — give yourself a day to adjust: drink lots of water, walk slowly, and skip the first-night bar crawl. The mountain cable car is another 2,000m up, so bring oxygen if you're prone to altitude sickness.",
    "The old town is packed during Chinese holidays (Golden Week, Spring Festival). Go in April, May or October for the best balance of weather and crowds.",
    "Wear proper walking shoes — it's all cobblestones, and you'll walk a LOT. High heels = regret. And carry your guesthouse's card with you; the lanes look identical after dark.",
  ],
  "related": [
    {"file":"guilin.html", "zh":"桂林", "en":"Guilin", "emoji":"🏔️", "desc":"Karst mountains, Li River scenery, outdoor adventure",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460324/li-river_lpbtrp.jpg"},
    {"file":"chengdu.html", "zh":"成都", "en":"Chengdu", "emoji":"🐼", "desc":"Pandas, hotpot, chill vibes, authentic local life",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460328/panda_yyeilx.jpg"},
  ],
})

# ============================================================ ORDOS
CITIES.append({
  "file": "ordos.html",
  "title": "Ordos Travel Guide — Ready? China!",
  "meta": "The honest guide to Ordos for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "鄂尔多斯", "en": "Ordos", "emoji": "🐎",
  "sub": "Grasslands, Mongolian culture, futuristic Ordos city",
  "meta_tags": ["★★★☆☆", "🗓 2–3 days", "Grasslands", "Mongolian culture"],
  "hero_bg": "",
  "hero_grad": "linear-gradient(135deg, #3a5a2a 0%, #7a9a4a 100%)",
  "why_emoji": "🐎",
  "why": [
    "Ordos is Mongolia-meets-the-21st-century: a city of futuristic architecture that was once dubbed the world's most famous 'ghost city', surrounded by singing-sand deserts, green grasslands and the spiritual heart of Mongolian culture — the Genghis Khan Mausoleum. It's the easiest place in China to experience the nomadic world: yurt stays, horse riding, roast lamb and a night sky full of stars.",
    "It's also a photographer's playground. Kangbashi district — built from scratch for a million people, home to a fraction of that — is a surreal museum of bold modern design with almost nobody around. Come for the desert and grassland, stay for the strangest, most photogenic cityscape in China."
  ],
  "top5": [
    {"id":"xiangshawan", "title":"Xiangshawan — Singing Sand Bay", "tag":"The desert that sings when you slide", "ph_emoji":"🏜️",
     "img":"",
     "story":"Xiangshawan sits on the eastern edge of the Kubuqi Desert, China's seventh-largest desert. Its centerpiece is a crescent dune 110 meters high and 400 meters wide that 'sings': when the dry sand shifts under your feet or you slide down its 45-degree slope, it produces a deep humming roar — one of only three such 'singing sand' sites in China.",
     "why":"Where else can you slide down a dune that literally plays music? Beyond the sand itself, the resort offers camel treks, dune buggies, a cable car over the dunes and two themed areas — adventure on one island, relaxation on the other. Stay until sunset and the desert puts on a light show.",
     "tip":"The singing effect only works on dry, windless days — skip it after rain. Buy the combo ticket (240 RMB with cable car + one island) rather than entry-only. Go at 4pm for golden light and cooler sand."},
    {"id":"genghis-khan", "title":"Genghis Khan Mausoleum", "tag":"The spiritual heart of Mongolia", "ph_emoji":"🏛️",
     "img":"",
     "story":"This is not a tomb but a cenotaph — Genghis Khan's real burial site remains unknown, as he wished. Since his death in 1227, the Mongolian people have maintained a mobile shrine of 'Eight White Yurts' in his honor, and the current complex was built in 1954 on the Gandel Grassland. It hosts over 60 ceremonial sacrifices a year and remains the most sacred site for Mongolians worldwide.",
     "why":"It's the emotional and cultural core of the Mongolian world — golden domes, white yurt-inspired halls, and a 4-km 'Sacred Path' lined with banners. The architecture is unlike anything else in China, and the annual ceremonies (with wrestling, horse racing and offerings) are a living tradition, not a show.",
     "tip":"Entry 90 RMB; go in the morning when ceremonies are more likely. The site is huge — take the internal shuttle. It's 70 km from the city, so combine it with grassland stops on a full-day tour."},
    {"id":"grassland", "title":"Ordos Grassland — horses &amp; yurts", "tag":"Sleep like a nomad under the stars", "ph_emoji":"⛺",
     "img":"",
     "story":"The Ordos Plateau rolls at 1,300–1,500 meters with cool summers, and its grasslands still hold working herder communities. At the tourist yurt camps you can ride horses across the steppe, try archery and milking, and sleep in a traditional felt ger — waking at dawn to horses grazing outside your door.",
     "why":"A yurt night on the grassland is the quintessential Inner Mongolia experience: horseback riding, mutton boiled over a campfire, and a night sky so clear the Milky Way looks fake. It's far less commercialized than Inner Mongolia's famous Hulunbuir — you'll often have the steppe to yourself.",
     "tip":"Best June–September when the grass is green. Nights drop to 10–15°C even in summer — bring warm layers. Book a yurt with a private bathroom if you can; the shared-facility ones are more rustic."},
    {"id":"kangbashi", "title":"Kangbashi — the 'ghost city'", "tag":"A futuristic city with almost nobody in it", "ph_emoji":"🏙️",
     "img":"",
     "story":"Construction of Kangbashi began in 2004 on empty grassland. Planned for nearly a million people, it had only 28,600 residents by 2010 — earning it global fame as the 'ghost city' of China. By 2024 the population reached 131,300, and the district became China's first national 4A urban scenic area, with 18 parks, the Grand Theater shaped like two open books, and the Ulan Moron River running through the middle.",
     "why":"It's a surreal urban laboratory: a city built from scratch with bold Mongolian-cultural architecture — the museum inspired by desert stones, the library like a giant stack of books — and almost no traffic. Summer averages a perfect 21°C, and the evening fountain-and-fireworks show on the river is free.",
     "tip":"Walk the Central Square at dusk, then watch the riverside fountain show (check times at the visitor center). Don't expect crowds — that's the whole point. Kangbashi is 25 km from the old city; taxis between the two take 30 minutes."},
    {"id":"naadam", "title":"Naadam festival", "tag":"Wrestling, horse racing &amp; archery", "ph_emoji":"🏹",
     "img":"",
     "story":"Naadam is the Mongolian 'festival of three manly sports' — wrestling, horse racing and archery — held across Inner Mongolia every summer. In Ordos, celebrations run through July–August with camel racing, traditional music, bonfire concerts and open-air feasts of whole roasted sheep.",
     "why":"It's the biggest, most authentic cultural event in Inner Mongolia: Mongolian wrestlers in traditional zodog jackets, child jockeys riding bareback at full gallop, and whole villages gathering under the sky. No museum can match standing in the middle of it.",
     "tip":"Dates vary by location each year but always fall July–August — check local announcements in spring. Book accommodation months ahead; grassland hotels sell out during Naadam. Hire a local guide for the ceremonies' meanings."}
  ],
  "stay": [
    {"name":"Kangbashi District", "badge":"Architecture &amp; cool summers",
     "desc":"The modern center with the city's best hotels, the museum and theater, and the riverfront. Summer averages 21°C — one of the coolest city centers in China. All the bold architecture is walkable from central hotels.",
     "metro":"No metro — taxis cheap (10–20 RMB within the district)", "landmark":"Ordos Museum, Grand Theater, Ulan Moron Lake",
     "hotel":"e.g. Shangri-La Ordos (luxury) · Crowne Plaza Ordos (upscale)"},
    {"name":"Dongsheng (old city)", "badge":"Budget &amp; transit hub",
     "desc":"The original city center: more affordable hotels, local restaurants and the main bus station for trips to Xiangshawan (55 km) and the grasslands. Grittier and more lived-in than Kangbashi.",
     "metro":"No metro — intercity buses to all scenic areas", "landmark":"Dongsheng center, bus terminal",
     "hotel":"e.g. Jinjiang Inn Dongsheng (budget) · Ordos Hotel (mid-range)"},
    {"name":"Ejin Horo Banner", "badge":"Culture &amp; self-driving",
     "desc":"Stay near the Genghis Khan Mausoleum and the surrounding Gandel Grassland — walk to the sacred site at dawn, then ride out to the grassland. Ideal for self-drivers; 70 km from Dongsheng.",
     "metro":"No metro — 40 km from Kangbashi airport", "landmark":"Genghis Khan Mausoleum, Gandel Grassland",
     "hotel":"e.g. mausoleum-area hotel (mid-range) · seasonal yurt camps (~400 RMB with meals)"},
    {"name":"Grassland yurt camps", "badge":"Nomad experience",
     "desc":"Yurt stays on the working grasslands — felt gers with modern bedding, bonfires and morning horse rides. Basic by hotel standards, unforgettable by every other measure.",
     "metro":"No metro — tour transport or self-drive", "landmark":"Open grassland, herder families",
     "hotel":"e.g. yurt camps on the Ordos Grassland (~300–500 RMB with meals)"}
  ],
  "eat": [
    {"name":"Whole Roasted Sheep", "zh":"烤全羊", "ph_emoji":"🍖",
     "img":"",
     "desc":"A whole sheep roasted over open fire for 3–4 hours until the skin is golden-crisp and the meat falls off the bone — the centerpiece of every Mongolian celebration.",
     "where":"🍽 Grassland yurt camps &amp; Kangbashi Mongolian restaurants · 800–1500 RMB per sheep (serves 8–10)"},
    {"name":"Hand-Grabbed Mutton", "zh":"手扒肉", "ph_emoji":"🍖",
     "img":"",
     "desc":"Fresh lamb boiled with just salt and a few spices, eaten with your hands and dipped in garlic-vinegar sauce — the purest possible taste of grassland lamb.",
     "where":"🍽 Mongolian restaurants across Ordos · ¥60–80 per portion"},
    {"name":"Mongolian Milk Tea &amp; Cheese", "zh":"奶茶与奶制品", "ph_emoji":"🥛",
     "img":"",
     "desc":"Salty milk tea brewed with brick tea, milk and a pinch of salt, served with fried dough twists, dried milk skin and milk tofu — a herder's breakfast, a meal in itself.",
     "where":"🍽 Yurt camps &amp; Mongolian teahouses · ¥15–25 per pot"},
    {"name":"Oat Noodles (Youmian)", "zh":"莜面", "ph_emoji":"🍜",
     "img":"",
     "desc":"A northern staple: oat dough rolled into thin strips or tubes, steamed and dipped in savory mutton or tomato sauce — hearty, healthy and utterly different from southern noodles.",
     "where":"🍽 Dongsheng old-city restaurants · ¥20–30"}
  ],
  "tips": [
    "Best window is May–October: July–August for green grasslands and Naadam, but Kangbashi stays a pleasant 21°C all summer. Bring a jacket for grassland nights year-round.",
    "Xiangshawan is 55 km from Dongsheng — allow a full day (taxi ~1 hour each way). Don't attempt the 'singing sand' after rain; it only sings when dry.",
    "Combine desert and grassland: base in Dongsheng for Xiangshawan day trips and in Kangbashi for city/museum days — the two districts are 30 minutes apart by car.",
  ],
  "related": [
    {"file":"beijing.html", "zh":"北京", "en":"Beijing", "emoji":"🏯", "desc":"History, culture, Great Wall — often paired with Inner Mongolia trips",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460303/great-wall_bczdqe.jpg"},
    {"file":"xian.html", "zh":"西安", "en":"Xi'an", "emoji":"🏺", "desc":"Ancient capital, Terracotta Army, Silk Road history",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460318/terracotta-army_pp8yhk.jpg"},
  ],
})

# ============================================================ PINGWU-BAIMA
CITIES.append({
  "file": "pingwu-baima.html",
  "title": "Pingwu Baima Travel Guide — Ready? China!",
  "meta": "The honest guide to Pingwu Baima for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "平武白马藏族乡", "en": "Pingwu Baima", "emoji": "🦅",
  "sub": "Baima Tibetan culture, mountain villages, feather headdress",
  "meta_tags": ["★★★★☆", "🗓 2 days", "Hidden ethnic gem", "Mountain escape"],
  "hero_bg": "",
  "hero_grad": "linear-gradient(135deg, #2a4a3a 0%, #5a8a6a 100%)",
  "why_emoji": "🦅",
  "why": [
    "Pingwu Baima is the most off-the-map destination on this site: a mountain valley in northern Sichuan where the Baima people — around 20,000 of them — have lived for over a thousand years, wearing white pheasant-feather hats and speaking a language of their own. A 2012 DNA study showed they descend from the ancient Di/Qiang peoples, making them one of East Asia's oldest living cultures.",
    "It's also the doorway to Wanglang, China's first giant-panda reserve — a pristine primeval forest where the wild panda population is densest on earth. Two days here means a Baima village bonfire, a panda-forest hike, and almost no other tourists. This is the real thing."
  ],
  "top5": [
    {"id":"baima-villages", "title":"Baima villages by Tianmu Lake", "tag":"A living culture, not a show", "ph_emoji":"🏘",
     "img":"",
     "story":"Villages like Paxijia (扒昔加古寨) hug the turquoise shore of Tianmu Lake with wooden watchtower houses that have stood for centuries. Baima women wear pleated red-and-white dresses and the white 'shaga' felt hat crowned with pheasant feathers — men wear a single straight feather (meaning honesty), women two or three curved ones (meaning beauty). Nights bring bonfires and the round dance (yuan-yuan-wu) that everyone joins.",
     "why":"This is a living culture: after the new expressway opened in 2024, village homestay income jumped from under 80,000 to 200,000+ RMB a year — the Baima are proud to host, not performing for tourists. The lake-and-snows setting is pure postcard, and the warmest welcome in Sichuan is here.",
     "tip":"Stay overnight — the bonfire singing and the mirror-still lake at sunrise are the two moments you'll remember forever. Ask before photographing people, and accept the 'za jiu' (bamboo-straw rice wine) toast — refusing is impolite."},
    {"id":"wanglang", "title":"Wanglang National Nature Reserve", "tag":"China's first giant-panda reserve", "ph_emoji":"🐼",
     "img":"",
     "story":"Founded in 1965 as China's very first giant-panda reserve, Wanglang covers 32,297 hectares of primeval spruce-fir forest at 2,363–4,983 meters. It protects the largest wild giant-panda population in China — the Minshan 'A' population — plus golden snub-nosed monkeys, takin and snow leopards: 62 mammal species and 271 bird species in total.",
     "why":"It's the best-researched wild panda habitat on the planet and deliberately stays raw: entry is quota-controlled, you ride in on a shared bus with a naturalist guide, and the forest belongs to pandas, not tour groups. You almost certainly won't see a panda — that's exactly why it's special.",
     "tip":"Book online well ahead through the official Giant Panda National Park channel — spots fill fast and private cars aren't allowed inside. Bring warm layers even in summer (average 2.4°C at altitude) and good shoes for the boardwalk trails."},
    {"id":"mask-dance", "title":"Caogai mask dance &amp; Baima songs", "tag":"A Stone-Age ritual, still performed", "ph_emoji":"🎭",
     "img":"",
     "story":"'Tiao Caogai' (跳曹盖) — the Baima mask dance — was listed as a national intangible cultural heritage in 2011. Every lunar New Year, dancers in white sheepskin coats leap and stamp wearing heavy carved black-bear spirit masks to drive out demons. Scholars trace the dance to Stone-Age hunting and totem worship; Baima songs, sung entirely in the Baima language, became a provincial heritage in 2023.",
     "why":"This is one of China's most primitive surviving ritual dances — a direct line to a culture older than the Han empire itself. You will never see anything like it anywhere else, and the fact that it's still performed in the villages, not on a stage, makes it extraordinary.",
     "tip":"The full ceremony runs lunar January 5–6 in the villages — plan around Chinese New Year and be a respectful observer. Outside festival season, local cultural troupes often perform shortened versions for visitors at the villages."},
    {"id":"embroidery", "title":"Baima embroidery &amp; costume craft", "tag":"Buy direct from the artisans", "ph_emoji":"🧵",
     "img":"",
     "story":"Baima costume-making is a recognized intangible heritage: pleated skirts, hand-woven flower belts, fish-bone breast plaques, and the white goat-wool 'shaga' hat — whose making is itself a provincial heritage craft. The feather on the hat honors a 6th-century legend in which golden pheasants screeched a warning that saved Baima soldiers from ambush.",
     "why":"Every detail carries meaning: one straight feather means honesty, curved feathers mean beauty, the fish-bone plaque wards off bad luck. Buying directly from village artisans keeps a nearly extinct craft alive — and you'll meet the makers while they work.",
     "tip":"Shop at village workshops and homestay studios rather than souvenir shops — you'll see the embroidery, felting and belt-weaving live. Hats run ¥100–300 depending on detail; embroidered belts make beautiful gifts."},
    {"id":"forest-hiking", "title":"Forest hiking &amp; waterfalls", "tag":"The anti-Jiuzhaigou", "ph_emoji":"🌲",
     "img":"",
     "story":"Trails from the villages wind up through old-growth forest to waterfall hollows and alpine meadows where dove trees bloom in April–May and wildflowers carpet the slopes by summer. Autumn turns larch and birch into sheets of gold against fresh snow, and summer air sits around a cool 20°C.",
     "why":"This is the same Minshan mountain chain as Jiuzhaigou, an hour deeper in — with none of the crowds. Just glacier-cut valleys, rushing streams and silence loud enough to hear your own heartbeat. For hikers, it's the hidden gem Sichuan forgot to advertise.",
     "tip":"Pick one 2–4 hour loop (toward Wanglang's buffer forest is the classic) and wear proper grip shoes — paths get slick after rain. Download offline maps; phone signal drops in the deep valleys."}
  ],
  "stay": [
    {"name":"Baima village homestays (Tianmu Lake)", "badge":"Immersive culture",
     "desc":"Family-run guesthouses in Paxijia and Yazhe Zaozu villages on the lake shore: wood-fired dinners, za jiu toasts and a bonfire round dance most evenings. Simple rooms (countryside inn, not resort), priceless lake-and-snow views.",
     "metro":"No metro — ~25–40 min drive from Wanglang's gate; lakeside loop roads", "landmark":"Tianmu Lake, Paxijia village, Wanglang gate",
     "hotel":"e.g. Tianyuan Inn (天缘客栈) · Huayaodai Inn (花腰带客栈) · ¥150–350/night incl. meals"},
    {"name":"Pingwu County town (Long'an)", "badge":"Comfort &amp; the Ming temple",
     "desc":"The county capital holds the 'Forbidden City of the mountains' — Bao'en Temple, built 1440–1446 entirely of golden nanmu wood with 9,999 carved dragons and the only still-rotating Ming scripture case in China. Stay here for reliable hotels and a comfortable first/last night.",
     "metro":"No metro — ~2.5h drive from Mianyang, ~3.5h from Chengdu via G8513", "landmark":"Bao'en Temple (4A site, ¥40), riverside morning market",
     "hotel":"e.g. Jiuzhou Jindu Hotel (resort-grade) · county hotels from ¥150–300"},
    {"name":"Inside Wanglang reserve", "badge":"Nature immersion",
     "desc":"Overnight inside the panda reserve by prior arrangement — you wake among the primeval forest and alpine wetlands that pandas call home. Tightly capped, requires a permit, books out months ahead.",
     "metro":"Reservation shuttle bus only; no private vehicles", "landmark":"Primeval spruce-fir forest, alpine wetlands, birding towers",
     "hotel":"e.g. reserve guesthouse (research-station style, simple)"}
  ],
  "eat": [
    {"name":"Za Jiu (bamboo-straw rice wine)", "zh":"咂酒", "ph_emoji":"🍶",
     "img":"",
     "desc":"A sweet fermented grain wine sipped through hollow bamboo straws from a shared jar — the ritual drink of every Baima toast and bonfire night.",
     "where":"🍽 Any village homestay or festival table"},
    {"name":"Buckwheat Pancakes &amp; Wild Honey", "zh":"荞麦饼蘸蜂蜜", "ph_emoji":"🥞",
     "img":"",
     "desc":"Crisp-edged buckwheat cakes dipped in Pingwu's famous high-altitude honey — earthy, floral and addictive. The perfect mountain breakfast.",
     "where":"🍽 Village inns &amp; county-town breakfast tables · ¥10–20"},
    {"name":"Cured Pork Rib &amp; Wild Mushroom Hotpot", "zh":"腊排骨汤锅", "ph_emoji":"🍲",
     "img":"",
     "desc":"High-mountain cured ribs slow-simmered with wild mushrooms into a milky, smoky broth — the defining winter dish of the Minshan foothills.",
     "where":"🍽 Rustic hotpot eateries in Pingwu town · ¥50–80 pp"},
    {"name":"Smoked Bacon &amp; Sausages", "zh":"老腊肉", "ph_emoji":"🥓",
     "img":"",
     "desc":"Dry-cured and pine-smoked pork with a deep, resinous aroma — sliced thin with garlic shoots or stir-fried with mountain greens.",
     "where":"🍽 Family restaurants county-wide · also sold at village markets to take home"}
  ],
  "tips": [
    "Book your Wanglang entry online in advance — the daily quota fills quickly and private cars can't enter. Bring warm layers for 2,400–5,000m altitudes; temperature swings are huge.",
    "Best months: late Oct–Nov for golden larches, June–Aug for 20°C forest escapes, April–May for dove flowers. Winter roads can ice up — check before driving.",
    "Respect the people: the Baima self-identify as 'Baima people', not simply Tibetans. Ask before photographing anyone, don't touch prayer flags or mani stones, and buy crafts directly from villagers.",
  ],
  "related": [
    {"file":"chengdu.html", "zh":"成都", "en":"Chengdu", "emoji":"🐼", "desc":"Pandas, hotpot, chill vibes — the gateway to western Sichuan",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460328/panda_yyeilx.jpg"},
    {"file":"chongqing.html", "zh":"重庆", "en":"Chongqing", "emoji":"🔥", "desc":"Cyberpunk city, hotpot capital, mountain drama",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460321/hongya-cave_kb6jvj.jpg"},
  ],
})

# ============================================================ CHANGXING
CITIES.append({
  "file": "changxing.html",
  "title": "Changxing Travel Guide — Ready? China!",
  "meta": "The honest guide to Changxing for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "长兴", "en": "Changxing", "emoji": "🍵",
  "sub": "Tea plantations, quiet lakes, local farm food",
  "meta_tags": ["★★☆☆☆", "🗓 1–2 days", "Tea culture", "Peaceful escape"],
  "hero_bg": "",
  "hero_grad": "linear-gradient(135deg, #2f4f2f 0%, #5a8a5a 100%)",
  "why_emoji": "🍵",
  "why": [
    "Changxing is the anti-tourist destination: a county of tea terraces, bamboo forests and Taihu Lake shoreline that Chinese travelers have quietly loved for centuries — and almost no foreign tourists know about. It's where China's first imperial tea factory was built in 770 AD, producing Zisun ('purple shoot') tea for the Tang court for nearly 900 years across five dynasties.",
    "And it's shockingly easy to reach: 25–35 minutes from Hangzhou and about an hour from Shanghai by high-speed rail. Come for a day of tea-picking and bamboo walks, stay overnight in a farmhouse among the terraces, and leave with the calmest photos of your whole China trip."
  ],
  "top5": [
    {"id":"guzhu-tea", "title":"Guzhu Mountain tea terraces", "tag":"Pick tea where the Tea Sage walked", "ph_emoji":"🍃",
     "img":"",
     "story":"Guzhu Mountain is where Lu Yu — the 'Tea Sage' who wrote The Classic of Tea, the world's first tea treatise — discovered Zisun tea over 1,200 years ago and recommended it to the Tang emperor. The terraced slopes still produce this prized purple-shoot tea, and you can walk the same fields, pick leaves in season, watch the pan-firing, and taste tea brewed with water from the nearby Jinsha Spring.",
     "why":"It's the most authentic tea-culture immersion in China: the actual birthplace of imperial tea, with the terraces cascading toward distant Taihu Lake. In spring you can pick your own leaves and have them roasted on the spot — a hands-on connection to a 1,200-year-old tradition.",
     "tip":"Visit late March to mid-April for the pre-Qingming harvest. Book a tea-picking experience through a farmhouse in Guzhu village in advance (~50–80 RMB per person). Wear sensible shoes — the terraces are steep."},
    {"id":"xianshan-lake", "title":"Xianshan Lake Wetland Park", "tag":"A flooded forest, straight out of a fairy tale", "ph_emoji":"🌊",
     "img":"",
     "story":"Dubbed the 'Oriental Amazon' by Chinese National Geographic, this wetland park spans 2,500 hectares of water forests, reed marshes and lotus ponds. A raised boardwalk threads through a flooded forest of dawn redwoods, where the rare reed parrotbill — nicknamed the 'panda of birds' — has been recorded, alongside egrets, wild ducks and mandarin ducks.",
     "why":"It's a rare chance to explore a flooded forest by boat in eastern China — drifting between tree trunks rising from still water, with lotus blooms in summer and mist in the morning. Quiet, beautiful, and almost completely unknown to foreign visitors.",
     "tip":"Combine the boat tour with the boardwalk walk — they show completely different sides of the wetland. Best light for photos is 8–10am when mist still hangs over the water."},
    {"id":"datang-tea-house", "title":"Datang Tribute Tea House", "tag":"China's first imperial tea factory", "ph_emoji":"🏛️",
     "img":"",
     "story":"Built in 770 AD by order of Emperor Daizong, this was China's first imperial tea factory — at its peak staffed by over 1,000 craftsmen who produced Zisun tea rushed by fast horse to the Tang capital (modern Xi'an) in time for the Qingming festival. The current complex is a meticulous reconstruction of the Tang-style compound, with tea-making exhibits, a Lu Yu pavilion and authentic Tang-era cliff inscriptions behind it.",
     "why":"This is ground zero for Chinese tea history — no other site in China connects you so directly to the Tang dynasty and to Lu Yu, who wrote The Classic of Tea while living on this very mountain. For anyone who loves tea, it's a pilgrimage.",
     "tip":"Entry 60 RMB; budget 2 hours. Don't miss the cliff inscriptions (moya shike) on the trail behind the complex — they're genuine Tang and Song carvings. The teahouse on site serves fresh Zisun tea with the view."},
    {"id":"ginkgo-corridor", "title":"Ten-Mile Ancient Ginkgo Corridor", "tag":"30,000 ginkgo trees turning gold", "ph_emoji":"🍂",
     "img":"",
     "story":"This 12.5-km valley in Xiaopu town holds over 30,000 ginkgo trees, including a 1,300-year-old 'Ginkgo King' and an 1,800-year-old 'Ginkgo Queen', threading through ancient villages and a Buddhist temple. A glass-bottom skybridge offers a panoramic view of the golden canopy.",
     "why":"When the ginkgoes turn in November, this becomes one of the most photographed landscapes in eastern China — a 12-kilometer tunnel of yellow that rivals Kyoto's autumn temples, with a tiny fraction of the tourists. It's the single best reason to time your trip to autumn.",
     "tip":"Peak color is mid-to-late November. Take the sightseeing mini-train (included in the 80 RMB ticket) to cover the length, then walk back through your favorite section. Stay overnight in a village minsu to see the corridor empty at dawn."},
    {"id":"taihu-resort", "title":"Taihu Longzhi Dream Resort", "tag":"A mega-resort on China's third-largest lake", "ph_emoji":"🎡",
     "img":"",
     "story":"Opened in stages from 2018, this 23-billion-RMB resort on Taihu Lake's southern shore bills itself as the world's largest comprehensive tourism complex: an animal world with 200+ species, a water park, an indoor snow world, a circus, and a recreated Tang-style 'ancient town' with nightly light shows and fireworks.",
     "why":"Even if theme parks aren't your thing, the free nightly water-and-light show on the lakefront is the best free evening entertainment in the region. And it's the closest you'll get to luxury accommodation with a Taihu Lake view.",
     "tip":"The light show starts around 8:20pm and is free to watch from the lakefront. With kids, the animal world (100 RMB) is excellent value. Avoid summer weekends unless you like crowds."}
  ],
  "stay": [
    {"name":"Shuikou tea valley (Guzhu village)", "badge":"Tea lovers &amp; slow travelers",
     "desc":"Dozens of family guesthouses sit among the tea fields and bamboo groves, ~20 minutes from the high-speed rail station. Many offer full-board packages — room + 3 home-cooked meals for 150–200 RMB per person per day. The best base for the Tribute Tea House and Guzhu Mountain.",
     "metro":"No metro — taxi from Changxing HSR Station (~25 RMB)", "landmark":"Datang Tribute Tea House, Guzhu tea terraces",
     "hotel":"e.g. Changxing Qinghe Minsu (~150 RMB) · Tea Language Farmhouse (~200 RMB full board)"},
    {"name":"Taihu Lake resort area", "badge":"Families &amp; resort lovers",
     "desc":"The Longzhi Dream complex offers the widest range of accommodation — from a panda-themed family hotel to lakeside resort rooms — with the water park, animal world and nightly shows steps away. 15 minutes from the county center.",
     "metro":"No metro — resort shuttle from the HSR station", "landmark":"Taihu Lake, Longzhi Dream, nightly light show",
     "hotel":"e.g. Longzhi Dream Joy World Hotel (400–700 RMB) · Animal World Panda Hotel (family, from 600 RMB)"},
    {"name":"Changxing county center", "badge":"Convenience &amp; transit",
     "desc":"The compact downtown near the HSR station has the usual reliable mid-range chains and the best local restaurants, with buses to all the scenic areas. The practical choice for a one-night stopover.",
     "metro":"No metro — local buses and taxis", "landmark":"HSR station, downtown dining streets",
     "hotel":"e.g. Atour Hotel Changxing (~300 RMB) · New Century Grand (~450 RMB)"}
  ],
  "eat": [
    {"name":"Taihu 'Three Whites'", "zh":"太湖三白", "ph_emoji":"🐟",
     "img":"",
     "desc":"The signature lake harvest: white fish, white shrimp and silver fish from Taihu Lake, steamed simply with ginger and scallion to highlight their delicate sweetness.",
     "where":"🍽 Lakeside farmhouse restaurants · ~60 RMB per dish"},
    {"name":"Silver Fish &amp; Eggs", "zh":"银鱼炒蛋", "ph_emoji":"🍳",
     "img":"",
     "desc":"Tiny translucent silver fish scrambled with farm eggs — light, fluffy and impossibly fresh. The taste of the lake in every bite.",
     "where":"🍽 Most farmhouse restaurants in Guzhu village · ¥30–40"},
    {"name":"Changxing Dry-Tossed Noodles", "zh":"长兴干挑面", "ph_emoji":"🍜",
     "img":"",
     "desc":"Hand-pulled noodles tossed in soy and lard oil, topped with crispy fish or braised pork — a beloved local breakfast, and some say the best in northern Zhejiang.",
     "where":"🍽 Shixiong Noodle Shop (downtown) · ~15 RMB"},
    {"name":"Bamboo Shoot Braised Pork", "zh":"笋干烧肉", "ph_emoji":"🍖",
     "img":"",
     "desc":"Dried bamboo shoots from the Guzhu forests slow-braised with pork belly until the shoots soak up the rich sauce and the meat melts — a farmhouse classic.",
     "where":"🍽 Tea Language Farmhouse &amp; Shuikou nongjiale · ~45 RMB"}
  ],
  "tips": [
    "Changxing is 25–35 minutes from Hangzhou East by high-speed rail (from ~40 RMB) — doable as a day trip, but staying overnight in a tea-field farmhouse is the real magic.",
    "Best times: March–April for tea-picking and bamboo shoots; mid-to-late November for the ginkgo corridor; October for golden autumn hills.",
    "Book a full-board farmhouse package (150–200 RMB/person/day including 3 meals) — better value than hotels, and the farmhouse cooking is how you taste Taihu fish and bamboo shoots properly.",
  ],
  "related": [
    {"file":"hangzhou.html", "zh":"杭州", "en":"Hangzhou", "emoji":"🌊", "desc":"West Lake, tea culture — 25 min from Changxing by train",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460323/west-lake_dslidh.jpg"},
    {"file":"shanghai.html", "zh":"上海", "en":"Shanghai", "emoji":"🌃", "desc":"Futuristic skyline, international food — ~1 hr from Changxing",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460304/bund_vqnbql.jpg"},
  ],
})

# ============================================================ HENGQIN
CITIES.append({
  "file": "hengqin.html",
  "title": "Hengqin Travel Guide — Ready? China!",
  "meta": "The honest guide to Hengqin for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "横琴", "en": "Hengqin", "emoji": "🎢",
  "sub": "Chimelong resort, Macau neighbor, entertainment island",
  "meta_tags": ["★★☆☆☆", "🗓 1–2 days", "Theme parks", "Night shows", "Near Macau"],
  "hero_bg": "",
  "hero_grad": "linear-gradient(135deg, #2a4a6a 0%, #5a8aaa 100%)",
  "why_emoji": "🎢",
  "why": [
    "Hengqin is a 106-square-km island in the Pearl River Delta, floating just 190 meters from Macau — and home to Chimelong Ocean Kingdom, the Guinness-certified world's largest aquarium, where you can watch an 8-meter whale shark drift past a record-breaking viewing window. It's the family-fun capital of southern China, with a theme-park resort, water parks and nightly fireworks.",
    "The genius of Hengqin is the two-country trick: cross the Lotus Bridge on foot and you're in Macau, eating Portuguese egg tarts and exploring UNESCO-listed streets — two destinations, one trip. Kids under 100cm enter Chimelong free, and the indoor park covers you on rainy days. This is China's easiest, most spectacular family day out."
  ],
  "top5": [
    {"id":"ocean-kingdom", "title":"Chimelong Ocean Kingdom", "tag":"The world's largest aquarium", "ph_emoji":"🐋",
     "img":"",
     "story":"Opened in 2014, Ocean Kingdom holds 5 Guinness World Records, including the world's largest aquarium — 48.75 million liters of water — and the biggest single tank on earth, a 22.7-million-liter whale-shark exhibit behind a 39.6m × 8.3m acrylic window. Its residents include whale sharks over 8 meters long, manta rays, belugas, polar bears and penguins, spread across 8 themed ocean zones.",
     "why":"This is the closest most people will ever get to a whale shark the size of a bus drifting silently past — plus record-breaking exhibits, a 100km/h roller coaster, a 5D castle theatre and a nightly fireworks spectacular, all in one ticket (adult ¥395, child ¥280).",
     "tip":"Go on a weekday and hit the Whale Shark Aquarium at 10am opening or after 6pm — queues swing from 5 to 45 minutes. Download the Chimelong app for live showtimes. Thrill coasters have height limits (~120cm)."},
    {"id":"tennis-center", "title":"Hengqin International Tennis Center", "tag":"Watch (or play) on WTA-grade courts", "ph_emoji":"🎾",
     "img":"",
     "story":"Designed by Populous — the firm behind Wimbledon's Centre Court — and opened in 2015, the center spans ~117,000 m² with a 5,000-seat stadium, a 1,500-seat show court and 16 practice courts. It has hosted the WTA Elite Trophy, the ATP Zhuhai Championship, Davis Cup ties and the 2025 Billie Jean King Cup Finals.",
     "why":"Where else can you stand on the same courts as WTA and ATP pros — then actually book a court and play? In the low season you might watch a world-class match with only a few hundred other fans, which is its own kind of magic.",
     "tip":"Check the event calendar before you book — tournament matches sell out, but practice courts are bookable via the Huafa Sports mini-app most days (open 8am–10pm)."},
    {"id":"night-show", "title":"Night fountain, drone &amp; fireworks show", "tag":"A Hollywood finale every night", "ph_emoji":"🎆",
     "img":"",
     "story":"Every night around 8pm, the lake in front of Ocean Kingdom becomes a 15–20-minute stage: over 100 drones, real fireworks, water-jetpack flyers, jet-ski stunts, a dancing music fountain and laser projections that turn the whale-shark building into a giant screen.",
     "why":"It's a full action-movie finale included with your park ticket — part fountain show, part fireworks, part drone display — and the single most photographed moment on the island. Pure spectacle, and the kids will never forget it.",
     "tip":"Claim a lakeside spot ~30 minutes early; the illuminated-float parade leads into the show, and the best angle faces the whale-shark building. Showtimes pause in heavy rain or typhoon alerts."},
    {"id":"walk-to-macau", "title":"Walk to Macau — Lotus Bridge &amp; the 24-hour port", "tag":"Two countries in one day", "ph_emoji":"🌉",
     "img":"",
     "story":"Hengqin Port runs 24 hours with 'one-stop joint inspection': you queue once and clear both China and Macau, typically in 30 seconds to 20 minutes. Across the Lotus Bridge you're on Macau's Cotai Strip — a ~10-minute taxi from the Venetian-style canals and the UNESCO-listed historic center. Macau's light rail now has a Hengqin Line, making the hop even easier.",
     "why":"It's the world's most effortless two-city day: breakfast in Zhuhai, pastéis de nata in Macau by lunch, back in time for the firework show at night. A genuine two-country adventure that takes zero planning.",
     "tip":"Bring your passport and make sure your China visa permits re-entry (or check China's 240-hour visa-free transit rules). Weekday mornings are fastest at the border; weekends see longer queues."},
    {"id":"duty-free", "title":"Duty-free &amp; border-zone shopping", "tag":"Macau bargains, border bargains", "ph_emoji":"🛍️",
     "img":"",
     "story":"Hengqin Port was approved for an inbound duty-free shop in January 2026 (up to ¥15,000 of duty-free goods for travelers entering from Macau — check its opening status), while an outbound duty-free shop already operates, and Macau's mega-mall Cotai resorts are 10 minutes away.",
     "why":"It's a shopping loop few tourists find: grab duty-free bargains, stroll through the newest, emptiest border crossing in the Pearl River Delta, and finish with a Portuguese-style photo at the Lopo Boutique plaza, all in one afternoon.",
     "tip":"Duty-free rules depend on your residency and travel frequency — keep receipts and declare what's required. If the new shop isn't open yet, Macau's Cotai malls remain the real retail draw."}
  ],
  "stay": [
    {"name":"Chimelong Resort zone", "badge":"Families &amp; park lovers",
     "desc":"On-island themed hotels inside the resort: the Penguin Hotel's rooms look into real penguin habitats, Hengqin Bay Hotel adds a 12,000 m² water world and dolphin academy, and the rooftop pool faces the nightly fireworks. You wake up, shuttle 5 minutes, and walk in early.",
     "metro":"Intercity rail + free resort shuttles; ~40 min taxi from central Zhuhai", "landmark":"Ocean Kingdom, Chimelong Spaceship, circus",
     "hotel":"e.g. Chimelong Penguin Hotel (~900–1200 RMB) · Hengqin Bay Hotel (~825+ RMB) · combo deals with park tickets"},
    {"name":"Novotown (Innovation Square)", "badge":"Rainy-day families &amp; mall convenience",
     "desc":"A mixed-use complex of shopping, cinema and indoor family fun — trampoline arenas, indoor karting, arcades — anchored by the 493-room Hyatt Regency. The perfect wet-weather base, ~10 minutes from both the border and the park.",
     "metro":"Free shuttles to Hengqin Port and the HK-Zhuhai-Macau Bridge port", "landmark":"Novotown mall, Hengqin Port, Cotai (Macau)",
     "hotel":"e.g. Hyatt Regency Hengqin (~571–800 RMB) with family-themed 'space' and 'animal' rooms"},
    {"name":"Hengqin Port &amp; Finance Island", "badge":"Macau day-trippers",
     "desc":"The closest hotels to the border and Macau's light-rail station — perfect if Macau is the priority and the park is a day trip. Evenings glow with the Portuguese-style Lopo plaza and the IFC tower across the water from Cotai.",
     "metro":"Walk to Hengqin Port (24h); LRT Hengqin Line to Macau ~2 min", "landmark":"Lotus Bridge, Cotai casinos, Hengqin Port",
     "hotel":"e.g. Artyzen Habitat Zhuhai (~450 RMB) · modern serviced apartments (~400 RMB)"},
    {"name":"Shenjing Village", "badge":"Backpackers &amp; budget foodies",
     "desc":"A fishing village 3.8 km from Ocean Kingdom where family homestays start around ¥180/night — a tenth of the on-resort price. The streets below are Hengqin's best cheap-food lane: charcoal-grilled oysters and seafood hotpots.",
     "metro":"One bus stop or ~10 min taxi to the park; ~15 min to the port", "landmark":"Ocean Kingdom, Flower Sea Corridor promenade",
     "hotel":"e.g. local guesthouses &amp; ocean-themed homestays ¥180–600"}
  ],
  "eat": [
    {"name":"Charcoal-Grilled Hengqin Oysters", "zh":"炭烧横琴蚝", "ph_emoji":"🦪",
     "img":"",
     "desc":"Hengqin's signature fat oysters, grilled over charcoal with garlic — sweet, briny and cheap. The island's name is practically synonymous with oysters.",
     "where":"🍽 Shenjing Village street stalls (~¥70 for 6) · Hao Daxian at Novotown"},
    {"name":"Oyster &amp; Chicken Hotpot", "zh":"生蚝鸡火锅", "ph_emoji":"🍲",
     "img":"",
     "desc":"A bubbling local pot where plump oysters poach into a rich chicken broth — the classic Hengqin comfort meal.",
     "where":"🍽 Hao Xuan Ge pressure-cooker oyster hotpot · ~¥80–90 pp"},
    {"name":"Cantonese Dim Sum", "zh":"粤式早茶", "ph_emoji":"🥟",
     "img":"",
     "desc":"Har gow and siu mai straight from the steamer — the classic Pearl River Delta breakfast ritual, done properly here.",
     "where":"🍽 Yijian Har Gow King (益健虾饺皇) in town · ¥60–100 pp"},
    {"name":"Macau-Style Egg Tart", "zh":"葡式蛋挞", "ph_emoji":"🥧",
     "img":"",
     "desc":"Blistering caramelized top, flaky crust — you're 20 minutes from the best egg tarts on earth. Cross the bridge and taste the difference.",
     "where":"🍽 Macau (20 min away) — Lord Stow's or Margaret's · ~¥10 per tart"}
  ],
  "tips": [
    "Typhoon season runs June–September — check forecasts 48h ahead. On storm days, swap outdoor rides for the indoor Chimelong Spaceship park or Novotown malls.",
    "Do Chimelong on a weekday and enter at opening: whale-shark queues jump from 5 to 45 minutes after lunch. Book tickets online; kids under 100cm enter free.",
    "Set up Alipay/WeChat Pay before you arrive (many kiosks are cashless), and carry your passport for the Macau hop — confirm your visa allows re-entry.",
  ],
  "related": [
    {"file":"chongqing.html", "zh":"重庆", "en":"Chongqing", "emoji":"🔥", "desc":"Cyberpunk city, hotpot capital, mountain drama",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460321/hongya-cave_kb6jvj.jpg"},
    {"file":"shanghai.html", "zh":"上海", "en":"Shanghai", "emoji":"🌃", "desc":"Futuristic skyline, international food, modernity",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460304/bund_vqnbql.jpg"},
  ],
})

# ============================================================ YIWU
CITIES.append({
  "file": "yiwu.html",
  "title": "Yiwu Travel Guide — Ready? China!",
  "meta": "The honest guide to Yiwu for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "义乌", "en": "Yiwu", "emoji": "🛒",
  "sub": "World's small-commodities market, crazy shopping",
  "meta_tags": ["★★☆☆☆", "🗓 1–2 days", "Shopping paradise", "Wholesale market"],
  "hero_bg": "",
  "hero_grad": "linear-gradient(135deg, #4a3a2a 0%, #8a6a3a 100%)",
  "why_emoji": "🛒",
  "why": [
    "Yiwu is the most mind-bending shopping destination on earth: a wholesale market of 75,000 booths selling 2.1 million product types across 6.4 million square meters — certified by the UN and World Bank as the world's largest small-commodity market. If you spent 3 minutes at every booth, 8 hours a day, it would take over a year to see it all.",
    "The market that started as a street-side stall line in 1982 is now the engine of global consumer goods — that $3 earring you bought anywhere in the world probably originated here. And since January 2026, a new high-speed link puts Yiwu just 33 minutes from Hangzhou. Come for the spectacle, stay for the street food, and leave with your luggage full of the world's cheapest souvenirs."
  ],
  "top5": [
    {"id":"trade-city", "title":"Yiwu International Trade City", "tag":"The world's largest wholesale market", "ph_emoji":"🏬",
     "img":"",
     "story":"From a 1982 street stall market, Yiwu has grown through six generations into the world's largest wholesale market: 6.4+ million square meters across five districts plus a new Digital Trade Center (opened October 2025). The UN, World Bank and Morgan Stanley have all called it the 'world's largest small-commodity market'; in 2024 it averaged 224,000 visitors a day, including 4,000+ foreign buyers from 230+ countries.",
     "why":"Even if you never buy a thing, walking this market is jaw-dropping — it's a city of products, where every object on earth seems to have a booth. It's a national 4A tourist attraction, free to enter, and unlike any shopping experience you've had in your life.",
     "tip":"Free entry, open 8:30am–5:30pm. Start at the tourist service center for a map. Most booths are wholesale-only (minimum orders apply), but many will sell a sample piece if you ask nicely. Bring a translator app — many vendors speak only Chinese."},
    {"id":"district-1", "title":"District 1 — toys, jewelry &amp; crafts", "tag":"80% of China's jewelry makers under one roof", "ph_emoji":"🧸",
     "img":"",
     "story":"The oldest and busiest district (opened 2002, 340,000 m², 8,000+ booths): the ground floor sells artificial flowers, the second hair accessories and jewelry, the third crafts and festive decorations. It gathers over 80% of China's jewelry manufacturers, with 5,000+ new designs released weekly.",
     "why":"This is where global fashion-accessory trends are born — if you've ever bought a $3 pair of earrings from a chain store anywhere in the world, they likely came from here. The sheer glittering density of merchandise is overwhelming in the best way.",
     "tip":"Visit on weekday mornings for the fewest crowds. Look for booths with 'MOQ' (minimum order quantity) signs if you're actually sourcing; otherwise, it's a fascinating window-shopping spectacle."},
    {"id":"district-2", "title":"District 2 — bags &amp; hardware", "tag":"Where Amazon sellers shop", "ph_emoji":"👜",
     "img":"",
     "story":"The second district (600,000 m², 8,000+ booths) covers bags and luggage, umbrellas, hardware tools, locks, small electronics and small appliances. The fourth floor hosts specialty pavilions offering factory-direct supply, and the district's bags-and-luggage zone alone feeds importers worldwide.",
     "why":"This is where Amazon sellers and importers come to source suitcases, power tools and kitchen gadgets by the container load. Even as a casual visitor, seeing the full breadth of 'Made in China' in one building is eye-opening — and fun.",
     "tip":"If you're sourcing, bring business cards and a notebook — vendors will quote MOQs and FOB prices on the spot. The fourth-floor regional pavilions are less crowded with higher-quality goods."},
    {"id":"district-4", "title":"Districts 3–4 — stationery, socks &amp; daily goods", "tag":"The world's biggest sock hub", "ph_emoji":"🧦",
     "img":"",
     "story":"District 3 (460,000 m²) concentrates stationery, office supplies, sports goods and cosmetics — its 1,900+ stationery vendors supply 100+ countries. District 4 (1.08 million m², 16,000+ booths) is the single largest district, selling socks, underwear, shoes and daily goods; its sock zone alone exports over 3 billion RMB a year.",
     "why":"District 4 is so large it could be a city by itself — the world's biggest sock-trading hub, where you'll find socks printed with everything from anime characters to national flags, sold by the thousand-pair carton. It's a museum of daily life, in bulk.",
     "tip":"District 4 is overwhelming — pick one category (socks on the lower floors, say) and focus. The buildings have internal elevated roads so delivery trucks drive right onto each floor; watch for vehicles in the corridors."},
    {"id":"district-5", "title":"District 5 &amp; the Digital Trade Center", "tag":"Imports, the future &amp; tourist shopping", "ph_emoji":"🤖",
     "img":"",
     "story":"District 5 (640,000 m², 7,000+ booths) focuses on imported goods, bedding and textiles, with a first-floor Import Pavilion stocking nearly 100,000 products from dozens of countries. The brand-new Digital Trade Center (opened October 2025, 1.25 million m²) is Yiwu's sixth-generation market: AI sourcing tools, livestream studios and virtual showrooms.",
     "why":"District 5's Import Pavilion is the easiest place in China to buy authentic foreign products — Italian wine, Japanese cosmetics, Russian chocolate — at near-wholesale prices. The Digital Trade Center shows where the world's market is heading, and it's genuinely cool.",
     "tip":"The Import Pavilion is the best place for tourist shopping — many items sell individually. The Digital Trade Center has a visitor experience zone with AI demos; 30 minutes is enough if you're not buying."}
  ],
  "stay": [
    {"name":"International Trade City area (Futian)", "badge":"Buyers &amp; market visitors",
     "desc":"The most practical base if the market is your goal: business hotels cluster around Futian Street, within a 5-minute walk of Districts 1–5, plus the Foreign Buyer Service Center and logistics offices.",
     "metro":"Jin-Yi-Dong light rail — International Trade City Station", "landmark":"Yiwu International Trade City, Digital Trade Center",
     "hotel":"e.g. Hilton Yiwu (upscale, ~600 RMB) · Yiwu Mansion (mid-range, ~350 RMB)"},
    {"name":"Binwang / downtown", "badge":"Nightlife &amp; food",
     "desc":"The old center around Binwang Market and Choucheng Square has the best night markets and street food — plus Yiwu's famous Korean Quarter (the city hosts a large Korean trading community). 10 minutes by taxi from the Trade City.",
     "metro":"Jin-Yi-Dong light rail — Yiwu Station; buses to Trade City 15 min", "landmark":"Binwang Night Market, Korean Quarter, Jiming Pavilion",
     "hotel":"e.g. Atour Hotel Binwang (~300 RMB) · Yiwu International Hotel (~280 RMB)"},
    {"name":"Fotang Ancient Town", "badge":"Culture seekers",
     "desc":"About 35 minutes south of downtown, staying in Fotang lets you experience the ancient town at its most atmospheric — empty old streets at dawn, temple bells, river mist — with boutique guesthouses in renovated merchant houses.",
     "metro":"No metro — bus 318 or taxi (~40 RMB)", "landmark":"Fotang Old Street, Wan Shan Floating Bridge, Water Street",
     "hotel":"e.g. Fotang Old Street minsu (~250 RMB) · local guesthouses (~120 RMB)"}
  ],
  "eat": [
    {"name":"Fotang Qianzhang Noodles", "zh":"佛堂千张面", "ph_emoji":"🍜",
     "img":"",
     "desc":"Thin wheat noodles in a clear broth topped with shredded dried tofu skin and pork — a 100-year-old local breakfast staple. Simple, savory, deeply comforting.",
     "where":"🍽 Xinghua Noodle Shop, Fotang Old Street · ~13 RMB"},
    {"name":"Brown Sugar Twists", "zh":"红糖麻花", "ph_emoji":"🥨",
     "img":"",
     "desc":"Yiwu's brown-sugar industry dates back over 700 years (a national intangible heritage) — twists and pastries drenched in freshly boiled brown-sugar syrup. Crunchy, chewy, not too sweet.",
     "where":"🍽 Yihong Brown Sugar Hall (Fotang) &amp; street vendors · ¥10–15"},
    {"name":"Korean BBQ", "zh":"韩式烤肉", "ph_emoji":"🥩",
     "img":"",
     "desc":"Yiwu's large Korean merchant community created an authentic Korean dining scene — grilled marinated short ribs, stone bibimbap and cold noodles that rival Seoul.",
     "where":"🍽 Korean Quarter near Binwang · ¥50–80 pp"},
    {"name":"Mixed Tofu Pudding", "zh":"豆花", "ph_emoji":"🥣",
     "img":"",
     "desc":"Silken tofu pudding, sweet (sugar syrup) or savory (soy sauce, chili oil, pickles) — a refreshing street snack, especially in summer.",
     "where":"🍽 Fotang old-street vendors &amp; Gongshang Night Market · ¥3–5"}
  ],
  "tips": [
    "The fastest train from Yiwu to Hangzhou East takes just 33 minutes (from ~45 RMB) — day-trip from Hangzhou, but the market deserves at least one full day, ideally two.",
    "The market is not designed for retail tourists — most booths need minimum orders of 50–500 pieces. For single-item shopping, head to District 5's Import Pavilion or the tourist center on District 1's ground floor.",
    "Download the 'Yiwu Go' (义乌购) app before visiting — it searches products and booth numbers, so you can navigate the 6.4-million-sqm complex without getting lost. Free Wi-Fi throughout.",
  ],
  "related": [
    {"file":"hangzhou.html", "zh":"杭州", "en":"Hangzhou", "emoji":"🌊", "desc":"West Lake, tea culture — 33 min from Yiwu by train",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460323/west-lake_dslidh.jpg"},
    {"file":"shanghai.html", "zh":"上海", "en":"Shanghai", "emoji":"🌃", "desc":"Futuristic skyline, international food, modernity",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460304/bund_vqnbql.jpg"},
  ],
})

# ============================================================ ZHANGJIAJIE
CITIES.append({
  "file": "zhangjiajie.html",
  "title": "Zhangjiajie Travel Guide — Ready? China!",
  "meta": "The honest guide to Zhangjiajie for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "张家界", "en": "Zhangjiajie", "emoji": "🏞️",
  "sub": "Avatar mountains, glass bridge, sandstone pillars",
  "meta_tags": ["★★☆☆☆", "🗓 2–3 days", "Avatar mountains", "Glass bridge", "National park"],
  "hero_bg": "",
  "hero_grad": "linear-gradient(135deg, #2a5a3a 0%, #5a9a6a 100%)",
  "why_emoji": "🏞️",
  "why": [
    "Zhangjiajie is where the landscapes of Chinese paintings turn out to be real: 3,000+ quartz-sandstone pillars rising up to 200 meters out of the forest — the rock formations that inspired the floating mountains of Avatar. It's China's original national park (est. 1982) and a UNESCO World Heritage Site, and it runs on superlatives: the world's tallest outdoor elevator, the world's longest and highest glass bridge, and a cableway to a 1,500-meter cliff-top skywalk.",
    "The scale is the thing — you need at least two full days and a good dose of patience with queues (go at 7am, trust us). Come for the pillars, the glass bridges and the mountain mist, and leave with photos that look Photoshopped — because they're not."
  ],
  "top5": [
    {"id":"national-forest-park", "title":"Zhangjiajie National Forest Park", "tag":"China's first national park — the Avatar mountains", "ph_emoji":"🏞️",
     "img":"",
     "story":"Established in 1982 as China's first national forest park, this is a forest of 3,000+ quartz-sandstone pillars that rise up to 200 meters from the treetops — formed by 300 million years of erosion. The most famous is 'Hallelujah Mountain' (1,074m), the inspiration for the floating peaks in James Cameron's Avatar. The whole area became a UNESCO World Heritage Site in 1992.",
     "why":"It's the single most alien landscape in China: pillars of rock wrapped in swirling mist, reached by cliff-top walkways, park shuttle buses and the world's tallest outdoor elevator. The light changes every hour — morning mist makes the pillars float, noon burns them gold, and sunset paints them pink. It genuinely looks like another planet.",
     "tip":"Enter at 7am when gates open — by 10am the tour buses arrive. Buy the 4-day park pass (¥228). The classic loop: Bailong Elevator up → Yuanjiajie (Avatar mountains) → walk to Tianzi Mountain → cable car down."},
    {"id":"tianmen-mountain", "title":"Tianmen Mountain &amp; the glass skywalk", "tag":"A cliff walk 1,430 meters up", "ph_emoji":"⛰️",
     "img":"",
     "story":"Tianmen ('Heaven's Gate') Mountain is a 1,519-meter peak reached by the world's longest cableway at 7.4 km — a 30-minute ride that feels like flying. The mountain's famous 131.5-meter-high natural arch ('Heaven's Gate Cave') is climbed via 999 steps, and its cliff-face walkways include glass-bottomed skywalks bolted to the sheer rock at 1,430 meters.",
     "why":"It's the full mountain experience in one day: the epic cableway, the 999-step climb through the heavenly gate, and a glass skywalk where you walk on air above the valley. On misty days the whole mountain becomes a sea of cloud — the most dramatic weather show in China.",
     "tip":"Book the cableway + ticket online (combined ~260 RMB). Go early (before 9am) — queues can hit 2 hours. The skywalk is free with entry; the 5 RMB shoe covers are mandatory. The 999 steps are worth it going up; take the elevator down."},
    {"id":"glass-bridge", "title":"Grand Canyon glass bridge", "tag":"Walk on air, 300 meters up", "ph_emoji":"🌉",
     "img":"",
     "story":"Opened in 2016, the Zhangjiajie Grand Canyon glass bridge spans 430 meters across a canyon 300 meters deep — the longest and highest glass-bottomed bridge in the world when it opened, built to hold 800 people at once. The bridge sways slightly, the glass is 4 cm thick, and walking across it is exactly as terrifying as it sounds.",
     "why":"It's a genuine bucket-list moment: standing on clear glass above a forested chasm, with the canyon walls on either side. Even if you're scared of heights, the adrenaline is the point — and the canyon below (with its own walking trail and waterfalls) is a beautiful park in its own right.",
     "tip":"Tickets are timed — book online for a specific slot and arrive 30 minutes early. Shoes with heels are banned (you get slippers). The bridge is 40 minutes from the national park; combine it with the canyon trail below for a full day."},
    {"id":"bailong-elevator", "title":"Bailong Elevator", "tag":"The world's tallest outdoor elevator — 326m", "ph_emoji":"🛗",
     "img":"",
     "story":"The Bailong ('Hundred Dragons') Elevator rises 326 meters up a sheer cliff face — the tallest outdoor elevator on earth, built in 2002 and certified by Guinness World Records. It carries visitors from the valley floor to the top of the pillar forest in under 2 minutes, with a glass front that gives a vertical view of the mountains as they drop away beneath you.",
     "why":"It's the most efficient (and most thrilling) way to reach the Avatar mountains: a 326-meter vertical ride that feels like taking off. The view from the top — the entire pillar forest laid out at your feet — is the payoff, and it saves you a 2-hour mountain climb.",
     "tip":"Go up at opening (7:30am) to skip the 1-hour queue — or use it DOWN at the end of the day when everyone is going up. Single ride ¥72 (plus park entry). The glass-fronted cabin is the one to wait for."},
    {"id":"ten-mile-gallery", "title":"Ten-Mile Gallery scenic train", "tag":"A train ride through the pillar forest", "ph_emoji":"🚂",
     "img":"",
     "story":"The Ten-Mile Gallery is a 5-km valley path through the heart of the pillar forest, where the rock formations have been named for what they resemble — the 'Old Man Gathering Herbs', the 'Three Sisters', the 'Turtle Watching the Sea'. A small scenic train runs the length of it, or you can walk the flat, easy trail in about an hour.",
     "why":"It's the most relaxed way to take in the pillar forest — a gentle walk or train ride with the mountains towering all around, far below the cliff-top crowds. The named formations are a fun game of imagination, and the trail is flat enough for everyone.",
     "tip":"Walk in, take the train back (or vice versa) — the train is ~38 RMB one-way. Go in the late afternoon for softer light on the pillars. It's in the Wulingyuan area, easy to combine with a half-day."}
  ],
  "stay": [
    {"name":"Wulingyuan (park entrance village)", "badge":"Best for park days",
     "desc":"The village at the park's main gate: everything you need for park days is 5 minutes away — the entrance, the Bailong Elevator bus stop, and the Ten-Mile Gallery trailhead. Restaurants and hotels line the main street, and the morning queue is yours to win.",
     "metro":"No metro — the village is walkable; taxis to town 40 min", "landmark":"National Park gate, Bailong Elevator, Ten-Mile Gallery",
     "hotel":"e.g. Pullman Zhangjiajie (5-star, 5 min from gate) · National Park Inn (family-run, owner plans your route)"},
    {"name":"Zhangjiajie city center", "badge":"Nightlife &amp; Tianmen days",
     "desc":"The city on the Li River has the airport, the train station and the Tianmen Mountain cableway — plus the best restaurants and night markets. Stay here for Tianmen days and easy airport/train connections; 40 minutes to the national park.",
     "metro":"No metro — bus/taxi to Wulingyuan (40 min)", "landmark":"Tianmen Mountain cableway, riverside, night market",
     "hotel":"e.g. Neodalle Zhangjiajie Wulingyuan (boutique, rooftop terrace) · city-center chains"},
    {"name":"Grand Canyon area", "badge":"Glass bridge focus",
     "desc":"A handful of guesthouses near the Grand Canyon glass bridge and its canyon trail — for travelers who want the bridge first thing, before the coach crowds arrive.",
     "metro":"No metro — taxi to Wulingyuan 30 min", "landmark":"Glass bridge, Grand Canyon trail",
     "hotel":"e.g. local guesthouses near the canyon entrance"}
  ],
  "eat": [
    {"name":"San Xia Guo hotpot", "zh":"三下锅", "ph_emoji":"🍲",
     "img":"",
     "desc":"Zhangjiajie's signature: three meats (usually pork, beef and lamb) in a spicy Tujia broth — the local answer to 'what's for dinner'. Order it everywhere; every restaurant claims theirs is best.",
     "where":"🍽 Local restaurants across Wulingyuan &amp; the city · ¥60–100 pp"},
    {"name":"Xiangxi Smoked Bacon", "zh":"湘西腊肉", "ph_emoji":"🥓",
     "img":"",
     "desc":"Hunan-style smoked pork belly — smoky, salty, slightly sweet — stir-fried with garlic shoots. The taste of the mountains, preserved the old way.",
     "where":"🍽 Tujia restaurants · ¥40–60"},
    {"name":"Sour Fish Soup", "zh":"酸汤鱼", "ph_emoji":"🐟",
     "img":"",
     "desc":"Tangy, spicy freshwater fish soup — a Tujia minority specialty that warms you up after a long, cold mountain day.",
     "where":"🍽 Tujia restaurants in Wulingyuan · ¥50–80"},
    {"name":"Mountain Chestnut Cake", "zh":"板栗饼", "ph_emoji":"🥮",
     "img":"",
     "desc":"Sweet cakes made from the chestnuts that grow in the mountains around Zhangjiajie — the classic snack to carry on trail days.",
     "where":"🍽 Street vendors at the park gates · ¥10–20"}
  ],
  "tips": [
    "Buy the 4-day park pass (¥228) — the park is huge and you need at least 2 full days. One day is not enough, trust us.",
    "AVOID Chinese national holidays completely — Golden Week and Spring Festival turn the glass bridge into a human parking lot. Go in April, May or September.",
    "Enter at 7am when gates open. By 10am the tour buses arrive and the queues get biblical. The morning mist between the pillars is the most magical — and most photogenic — time.",
  ],
  "related": [
    {"file":"guilin.html", "zh":"桂林", "en":"Guilin", "emoji":"🏔️", "desc":"Karst mountains, Li River scenery — China's other iconic landscape",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460324/li-river_lpbtrp.jpg"},
    {"file":"chongqing.html", "zh":"重庆", "en":"Chongqing", "emoji":"🔥", "desc":"Cyberpunk city, hotpot capital — combine with a Yangtze cruise",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460321/hongya-cave_kb6jvj.jpg"},
  ],
})
