import os
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""City data batch A: shanghai, xian, chengdu, chongqing, guilin, hangzhou, quanzhou, dunhuang."""

CITIES = []

# ============================================================ SHANGHAI
CITIES.append({
  "file": "shanghai.html",
  "title": "Shanghai Travel Guide — Ready? China!",
  "meta": "The honest guide to Shanghai for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "上海", "en": "Shanghai", "emoji": "🌃",
  "sub": "Futuristic skyline, international food, modernity",
  "meta_tags": ["★☆☆☆☆", "🗓 3–4 days", "Most international", "Easy for beginners"],
  "hero_bg": "https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460304/bund_vqnbql.jpg",
  "hero_grad": "linear-gradient(135deg, #16213e 0%, #3b5b92 100%)",
  "why_emoji": "🌃",
  "why": [
    "Shanghai is the easiest place in China for a first-timer — English is everywhere, the metro runs like clockwork, and almost every app you need works here. But don't mistake easy for boring: for over a century this has been China's most international city, a place where a 1920s French villa sits around the corner from a 600-meter supertall skyscraper.",
    "The Bund gives you the world's greatest skyline show for free, the old French Concession is made for slow afternoons and coffee, and the food scene runs from street-side soup dumplings to Michelin-starred tasting menus. If you only have a week in China, spend it here — and if you have more, Shanghai is the perfect first stop before the rest of the country."
  ],
  "top5": [
    {"id":"bund", "title":"The Bund &amp; the Pudong skyline", "tag":"Colonial past meets the future", "ph_emoji":"🌃",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460304/bund_vqnbql.jpg",
     "alt":"The Bund waterfront and Pudong skyline at night",
     "story":"The Bund is a 1.5-km strip of 52 colonial-era buildings from the 1920s–30s — banks and trading houses built by British, French, American and Japanese firms when Shanghai was the 'Paris of the East'. Across the Huangpu River, Pudong's skyline rose from farmland in the 1990s: the Oriental Pearl Tower (1994), the 492-m Shanghai World Financial Center (2008) and the 632-m Shanghai Tower (2015), China's tallest building.",
     "why":"It's the only place on earth where you can stand in front of century-old European architecture and look directly at a fully futuristic Chinese skyline — the past and the future of Shanghai in a single glance. Come at night when the towers light up, and again at dawn when it's just you, the river, and the city waking up.",
     "tip":"The Bund is free and open 24/7. Go at 7pm for the full light show, then walk two blocks back into Nanjing Road for street food. For the classic postcard view of the Bund itself, cross to Pudong and look back from Lujiazui."},
    {"id":"yu-garden", "title":"Yu Garden &amp; the old city", "tag":"A Ming dynasty garden in the heart of town", "ph_emoji":"🏯",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460304/yu-garden_bh3jqo.jpg",
     "alt":"Yu Garden classical pavilions",
     "story":"Yu Garden was built between 1559 and 1577 by Pan Yunduan, a Ming-dynasty official, as a private garden for his parents — 'Yu' means 'peace and comfort'. It's a masterpiece of classical Chinese garden design: rockeries, carp ponds, zigzag bridges and dragon walls that hide the garden's true size (about 2 hectares) behind every turn.",
     "why":"It's the finest example in Shanghai of a classical Chinese garden — the kind of delicate pavilions-and-ponds scene you see in paintings. Around it, the old city walls are gone but the old-city lanes survive: tiny shops selling tea, jade and calligraphy brushes, all squeezed under traditional roofs.",
     "tip":"Arrive at opening (9am) to beat the crowds. Right outside the gates, the snack street Nanxiang serves the legendary xiaolongbao — get the crab-roe version. Garden entry is 40 RMB."},
    {"id":"french-concession", "title":"French Concession", "tag":"Plane trees, cafés &amp; old villas", "ph_emoji":"☕",
     "img":"",
     "story":"From 1849 to 1943 this leafy district was the French Concession, and it still feels European — wide avenues shaded by 100-year-old plane trees, alleys of 1920s townhouses, and some of Shanghai's most beautiful streets (Wukang Road is the star). It was home to artists, writers and spies; Sun Yat-sen and Soong Ching-ling both lived here.",
     "why":"This is the Shanghai locals choose for weekend strolls: coffee on every corner, tiny galleries, vintage shops and tree-dappled streets with zero skyscrapers. It's the closest China gets to a Parisian afternoon, and the best place to slow down after the Bund's sensory overload.",
     "tip":"Rent a shared bike (Meituan or HelloBike, ~1.5 RMB per 30 min) and wander without a map — get lost on purpose. Wukang Road, Anfu Road and Tianzifang's alleys are the highlights. Allow half a day."},
    {"id":"shanghai-museum", "title":"Shanghai Museum", "tag":"One of China's best — and free", "ph_emoji":"🏺",
     "img":"",
     "story":"Founded in 1952, the Shanghai Museum moved in 1996 into a striking round-building-with-square-base design that echoes the ancient Chinese belief 'heaven is round, earth is square'. Its collection of over one million pieces is ranked among the best in China, with world-class galleries of bronzes, ceramics, calligraphy, jade and Ming-Qing furniture.",
     "why":"Chinese museums rarely offer this combination: world-class artifacts, English labels, free entry, and air conditioning when the summer heat hits. The bronze gallery alone — ritual vessels up to 3,000 years old — is worth the trip. It's the perfect rainy-day or escape-the-heat move.",
     "tip":"Entry is free but you must reserve online (WeChat mini-program or official site) with your passport — book a few days ahead in high season. Allow 2–3 hours; the bronze and ceramic galleries are the unmissable ones."},
    {"id":"tianzifang", "title":"Tianzifang", "tag":"Artistic alleyways in the old lanes", "ph_emoji":"🎨",
     "img":"",
     "story":"Tianzifang is a warren of shikumen (stone-gate) lane houses from the 1930s that artists began moving into around 1998, turning it into Shanghai's most creative quarter. Today its alleys hide hundreds of tiny studios, galleries, craft shops, cafés and bars — a living, working neighborhood rather than a reconstructed 'old town'.",
     "why":"Unlike polished tourist streets elsewhere, Tianzifang feels real — residents still hang laundry above the shops, and behind every doorway is something handmade and unexpected. It's the most atmospheric place in Shanghai to shop for gifts, watch artisans work, and duck into a laneway bar at night.",
     "tip":"Go on a weekday (weekends are shoulder-to-shoulder). The alleys are a maze — pick one direction and just wander. For the classic view, climb to one of the rooftop bars around the edge of the maze."}
  ],
  "stay": [
    {"name":"The Bund / Nanjing Road", "badge":"First-timers &amp; skyline views",
     "desc":"Wake up to the Pudong skyline from your window, stroll the Bund at dawn before the crowds, and step out your door onto Nanjing Road — Shanghai's famous shopping street. Metro Line 2 and 10 run right through, and the old city with Yu Garden is a 15-minute walk.",
     "metro":"Line 2/10 · East Nanjing Road", "landmark":"The Bund, Nanjing Road",
     "hotel":"e.g. Les Suites Orient (mid-range, river views) · Peace Hotel (legendary art-deco landmark)"},
    {"name":"People's Square / Huangpu", "badge":"Central &amp; convenient",
     "desc":"The dead-center of Shanghai: Shanghai Museum on one side, the old city and Yu Garden to the south, and the French Concession a 10-minute taxi ride away. Two major metro lines cross here, and prices are more reasonable than the Bund.",
     "metro":"Lines 1/2/8 · People's Square", "landmark":"Shanghai Museum, Yu Garden, Nanjing Road",
     "hotel":"e.g. JW Marriott Shanghai at Tomorrow Square (landmark) · budget chains around the square"},
    {"name":"French Concession (Xuhui / Jing'an)", "badge":"Café &amp; architecture lovers",
     "desc":"The most atmospheric place to stay — tree-lined streets, boutiques and coffee shops, and the city's best brunch scene. It's less central for sightseeing but perfect if you want to feel the real Shanghai rhythm. Wukang Road's historic mansions are right outside.",
     "metro":"Lines 1/7/10/11 · Changshu Rd / Shanghai Library", "landmark":"Wukang Road, Tianzifang, Anfu Road",
     "hotel":"e.g. The Puli Hotel (luxury, Jing'an) · Capella Shanghai (restored shikumen villas, splurge)"},
    {"name":"Lujiazui (Pudong)", "badge":"Modern skyline &amp; business",
     "desc":"Stay inside the skyline you came to see: the financial district where the Shanghai Tower and Oriental Pearl live. Prices are high, and crossing the river adds 20 minutes to the Bund, but the night views from a high floor are unbeatable.",
     "metro":"Line 2 · Lujiazui", "landmark":"Shanghai Tower, Oriental Pearl, IFC Mall",
     "hotel":"e.g. Grand Hyatt Shanghai (tower views) · Mandarin Oriental Pudong (luxury)"}
  ],
  "eat": [
    {"name":"Xiaolongbao", "zh":"小笼包", "ph_emoji":"🥟",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460304/xiaolongbao_ndfdw3.jpg",
     "alt":"Steamed soup dumplings xiaolongbao",
     "desc":"Delicate steamed dumplings holding hot pork-and-gelatin broth inside. The Shanghai ritual: bite a small hole, slurp the soup, then eat the rest with vinegar and ginger.",
     "where":"🍽 Jia Jia Tang Bao (Michelin-mentioned) · Yu Garden snack street · ¥15–30 per basket"},
    {"name":"Shengjianbao", "zh":"生煎包", "ph_emoji":"🥟",
     "img":"",
     "desc":"Pan-fried pork buns with a crispy golden bottom, juicy filling and a burst of hot soup — xiaolongbao's heartier, crunchier cousin, and the true local breakfast.",
     "where":"🍽 Da Hu Chun (legendary since 1932) · ¥12–20 per order of 4"},
    {"name":"Hairy Crab", "zh":"大闸蟹", "ph_emoji":"🦀",
     "img":"",
     "desc":"A seasonal obsession (Oct–Nov only): small lake crabs prized for their creamy roe and sweet meat. Locals plan entire dinners around them — worth scheduling your trip for.",
     "where":"🍽 Wang Bao He on Fuzhou Road · ¥80–200 per crab in season · book ahead"},
    {"name":"Scallion Oil Noodles", "zh":"葱油拌面", "ph_emoji":"🍜",
     "img":"",
     "desc":"Springy noodles tossed with scallion-infused oil and soy — deceptively simple, deeply comforting, and the taste of a Shanghai home kitchen.",
     "where":"🍽 Any local canteen or noodle shop · ¥15–25"}
  ],
  "tips": [
    "Get a Shanghai metro card or just tap with your phone (Alipay/WeChat Pay) — the network is huge, cheap (~3–6 RMB) and fully in English. Avoid taxis during rush hour.",
    "The Bund at night and the Bund at 7am are two completely different experiences — do both. Night for the lights, dawn for the colonial architecture and the tai chi crowd.",
    "Almost everything in Shanghai can be paid with Alipay or WeChat Pay; for the small old-city snack stalls carry 50–100 RMB in cash as backup.",
  ],
  "related": [
    {"file":"hangzhou.html", "zh":"杭州", "en":"Hangzhou", "emoji":"🌊", "desc":"Serenity, West Lake, tea culture, easy day trips",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460323/west-lake_dslidh.jpg"},
    {"file":"beijing.html", "zh":"北京", "en":"Beijing", "emoji":"🏯", "desc":"History, culture, Great Wall, Chinese civilization",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460303/great-wall_bczdqe.jpg"},
  ],
})

# ============================================================ XI'AN
CITIES.append({
  "file": "xian.html",
  "title": "Xi'an Travel Guide — Ready? China!",
  "meta": "The honest guide to Xi'an for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "西安", "en": "Xi'an", "emoji": "🏺",
  "sub": "Ancient history, Terracotta Army, Silk Road",
  "meta_tags": ["★★☆☆☆", "🗓 2–3 days", "Unmissable history", "Street food heaven"],
  "hero_bg": "https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460318/terracotta-army_pp8yhk.jpg",
  "hero_grad": "linear-gradient(135deg, #5a3a1e 0%, #9a6b3a 100%)",
  "why_emoji": "🏺",
  "why": [
    "Xi'an was China's capital for over 1,000 years across 13 dynasties — the longest of any city — and it's where the Silk Road began. Emperors ruled here when London was a village, and the evidence is still standing: the world's largest ancient city wall, pagodas built by a Tang-dynasty monk, and an army of 8,000 terracotta soldiers guarding a tomb for 2,200 years.",
    "But Xi'an isn't only ancient. The Muslim Quarter is one of China's great street-food bazaars, the city wall is the best place in the country to rent a bike, and the metro now links it all together. History nerds, food lovers and first-timers alike leave impressed — it's the perfect second stop after Beijing."
  ],
  "top5": [
    {"id":"terracotta", "title":"Terracotta Army", "tag":"8,000 warriors guard an emperor's tomb", "ph_emoji":"🏺",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460318/terracotta-army_pp8yhk.jpg",
     "alt":"The Terracotta Army warriors",
     "story":"In 1974, farmers digging a well near Xi'an stumbled onto the greatest archaeological discovery of the 20th century: an underground army built around 210 BC for Qin Shi Huang, China's first emperor. So far over 8,000 life-size soldiers, 130 chariots and 670 horses have been found, each warrior with a unique face — no two are alike. The entire site, a UNESCO World Heritage Site since 1987, covers 56 square kilometers.",
     "why":"This is one of the world's true wonders — a silent army that has waited 2,200 years for visitors, built by over 700,000 laborers. Pit 1 alone holds 6,000 warriors in battle formation, and the sheer scale makes you understand why the first emperor thought he could conquer death itself.",
     "tip":"Go early (opens 8:30am) and head straight to Pit 1 before the tour groups arrive. It's 1 hour from the city — take public bus 306 (游5) from the train station for 7 RMB, not the 200 RMB tourist bus. Allow 3–4 hours."},
    {"id":"city-wall", "title":"Ancient City Wall", "tag":"Ride a bike around 14th-century ramparts", "ph_emoji":"🚲",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460305/xi_an-city-ride_tydbkn.jpg",
     "alt":"Cycling on top of the Xi'an city wall",
     "story":"Xi'an's city wall was built 1370–1378 by the first Ming emperor, on foundations laid in the Tang dynasty. It's the best-preserved city wall in China — and the largest anywhere: a 13.7-km rectangle, 12–14 meters thick at the base, with a 12-meter-wide top and a moat on three sides. Four grand gates and 98 watchtowers ring the old city.",
     "why":"Nowhere else in China can you cycle the full circumference of an intact ancient city wall. The 13.7-km loop takes about 1.5–2 hours on a rented bike, with views over tiled old-city roofs on one side and modern Xi'an on the other — especially magical at sunset.",
     "tip":"Rent a bike on the wall (45 RMB for 2 hours, or 100 RMB deposit) — bikes are available at every gate. Go 2 hours before sunset and time your loop to finish as the lights come on. Entrance is 54 RMB."},
    {"id":"muslim-quarter", "title":"Muslim Quarter (Huimin Jie)", "tag":"China's best street-food bazaar", "ph_emoji":"🥙",
     "img":"",
     "story":"The Muslim Quarter has been home to Xi'an's Hui Muslim community for over a thousand years — descendants of Silk Road traders from Persia and Central Asia who married locally and stayed. Its maze of alleys behind the 14th-century Drum Tower is now China's most famous food street: lamb skewers, roujiamo, biangbiang noodles, dates, and dried fruit piled high under neon signs.",
     "why":"This is where Xi'an's street-food soul lives. The main strip is touristy, but one alley deeper and you're eating where locals eat — hand-pulled noodles, bubbling paomo soup, and skewers grilled over charcoal. It's the perfect evening after a day of history.",
     "tip":"Skip the shops right on the main street; wander the side alleys (Xiyangshi, Beiyuanmen) for better food and prices. Go at 6pm when it's lively but not yet packed. Bring small cash for the stalls."},
    {"id":"big-wild-goose-pagoda", "title":"Big Wild Goose Pagoda", "tag":"Where a Tang monk stored his scriptures", "ph_emoji":"🛕",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460305/big-wild-goose-pagoda_bofjs4.jpg",
     "alt":"Big Wild Goose Pagoda",
     "story":"Built in 652 AD, this 64.5-meter, seven-story brick pagoda was commissioned by the great Tang-dynasty monk Xuanzang to store the Buddhist scriptures he carried back from 17 years of travel across India — the journey that later inspired the novel 'Journey to the West'. The surrounding Da Ci'en Temple was once one of the most important monasteries in China.",
     "why":"It's a direct link to one of history's greatest travelers — and the pagoda itself, elegant and uncluttered after 1,300 years, is a masterpiece of Tang architecture. The Daming Palace ruins nearby show how vast Tang Xi'an was: the Tang capital was once the largest city on earth, with a million residents.",
     "tip":"Come in the evening: the square in front hosts the famous music fountain show (usually 7pm and 9pm, free), and the pagoda glows gold against the night sky. Entry 40 RMB for the temple; climbing the pagoda is an extra 30 RMB."},
    {"id":"shaanxi-museum", "title":"Shaanxi History Museum", "tag":"130,000 years of history — free entry", "ph_emoji":"🏛",
     "img":"",
     "story":"Xi'an's treasure vault: over 370,000 artifacts spanning from prehistoric times to the Qing dynasty, including Zhou-dynasty bronzes, Tang-dynasty gold and silver, and thousands of pieces unearthed right in the city. Its collection is so rich that only a fraction is ever on display at once.",
     "why":"If you want to understand why Xi'an matters — and see the actual objects behind all that history — this is the place. The Tang gold and silver gallery alone is worth the visit, and unlike many Chinese museums, the collection is world-class even by international standards.",
     "tip":"Entry is FREE but quota-limited: reserve online (official WeChat mini-program) with your passport at least 3 days ahead. Go right at opening (9am). Allow 2–3 hours; the Tang galleries on the second floor are the highlights."}
  ],
  "stay": [
    {"name":"Inside the City Wall (Bell Tower area)", "badge":"Best for first-timers",
     "desc":"The historic heart: the Bell and Drum Towers, the Muslim Quarter's food alleys, and the old-city atmosphere are all within walking distance. Metro Line 2 runs along the wall's north-south axis, linking you to the train station and the Terracotta Army bus.",
     "metro":"Lines 2/4/6 · Bell Tower", "landmark":"Bell Tower, Drum Tower, Muslim Quarter",
     "hotel":"e.g. Sofitel Legend People's Grand (1950s landmark) · Eastern House Boutique (great value near Bell Tower)"},
    {"name":"South Gate (Yongningmen)", "badge":"Quiet &amp; upscale",
     "desc":"South of the Bell Tower along the wall, this area has a more refined feel — trendy cafés, galleries and boutique hotels tucked into old courtyards, with direct access to the wall's South Gate bike rental and the Yongningmen metro.",
     "metro":"Lines 2 · Yongningmen", "landmark":"South Gate, Shuyuanmen old street, De Fu Xiang",
     "hotel":"e.g. Somerset Xindicheng Serviced Residence (apartments) · boutique courtyard hotels"},
    {"name":"Qujiang New District", "badge":"Sightseers &amp; evening shows",
     "desc":"The modern cultural district around the Big Wild Goose Pagoda and the Tang Paradise park — wide avenues, night fountain shows, and the city's most impressive modern architecture. About 15–20 minutes by taxi to the old city.",
     "metro":"Lines 3/4 · Dayanta", "landmark":"Big Wild Goose Pagoda, Tang Paradise, Qujiang pool",
     "hotel":"e.g. Wyndham Grand Xi'an South (5-star near the pagoda) · mid-range chains along Yanta Road"},
    {"name":"Xi'an North Railway Station area", "badge":"High-speed train transfer",
     "desc":"If you're arriving by bullet train (from Beijing 4.5h, Chengdu 3h) or flying in, the north station area is modern, cheap and convenient — though it's a 30-minute metro ride from the old city's sights.",
     "metro":"Lines 2/4 · North Railway Station", "landmark":"High-speed rail hub, 3-km to airport bus",
     "hotel":"e.g. Xi'an Jinhua Hotel · business chains (Holiday Inn Express)"}
  ],
  "eat": [
    {"name":"Roujiamo", "zh":"肉夹馍", "ph_emoji":"🥙",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460306/roujiamo-chinese-burger_kowuyb.jpg",
     "alt":"Roujiamo Chinese burger",
     "desc":"Spiced braised pork, chopped fine and stuffed into a crisp, griddled flatbread — often called the world's first hamburger. Xi'an's most iconic snack.",
     "where":"🍽 Muslim Quarter stalls · ¥10–15 each · order the 'lean' (纯瘦) or 'half-fat' (肥瘦) version"},
    {"name":"Yangrou Paomo", "zh":"羊肉泡馍", "ph_emoji":"🍲",
     "img":"",
     "desc":"The soul food of Xi'an: you tear flatbread into crumbs, the kitchen simmers it in rich lamb broth, and you eat it with pickled garlic and chili — a ritual meal that takes patience and rewards it.",
     "where":"🍽 Lao Sun Jia (老孙家) or local paomo shops · ¥30–50"},
    {"name":"Biangbiang Noodles", "zh":"biangbiang面", "ph_emoji":"🍜",
     "img":"",
     "desc":"Hand-ripped belt noodles as wide as your palm, tossed with chili oil, garlic and vinegar. The name's Chinese character has 58 strokes — the most complex in the language.",
     "where":"🍽 Muslim Quarter noodle houses · ¥15–25"},
    {"name":"Lamb Skewers", "zh":"羊肉串", "ph_emoji":"🍢",
     "img":"",
     "desc":"Charcoal-grilled lamb skewers dusted with cumin and chili — the soundtrack of the Muslim Quarter at night. Order them in tens, eat them standing up.",
     "where":"🍽 Beiyuanmen alley, Muslim Quarter · ¥3–5 per skewer"}
  ],
  "tips": [
    "The Terracotta Army deserves 3–4 hours and an early start — take public bus 306 (游5) from the train station for 7 RMB and ignore the touts offering 'express tours'.",
    "Ride the city wall at sunset, not midday — the 13.7 km loop takes ~2 hours and the golden light over the old city is unforgettable.",
    "The Muslim Quarter is at its best after 6pm. Go deeper than the main street for the real food; and yes, roujiamo really is as good as everyone says.",
  ],
  "related": [
    {"file":"beijing.html", "zh":"北京", "en":"Beijing", "emoji":"🏯", "desc":"History, culture, Great Wall, Chinese civilization",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460303/great-wall_bczdqe.jpg"},
    {"file":"chengdu.html", "zh":"成都", "en":"Chengdu", "emoji":"🐼", "desc":"Pandas, hotpot, chill vibes, authentic local life",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460328/panda_yyeilx.jpg"},
  ],
})

# ============================================================ CHENGDU
CITIES.append({
  "file": "chengdu.html",
  "title": "Chengdu Travel Guide — Ready? China!",
  "meta": "The honest guide to Chengdu for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "成都", "en": "Chengdu", "emoji": "🐼",
  "sub": "Pandas, hotpot, chill vibes, authentic local life",
  "meta_tags": ["★★☆☆☆", "🗓 3–5 days", "Pandas!", "Best food city", "Laid-back"],
  "hero_bg": "https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460328/panda_yyeilx.jpg",
  "hero_grad": "linear-gradient(135deg, #2f4f2f 0%, #5a8a5a 100%)",
  "why_emoji": "🐼",
  "why": [
    "Chengdu is the only place on earth where you can watch giant pandas eating bamboo 20 meters away, then sit in a 100-year-old teahouse and sip jasmine tea for the entire afternoon — and nobody will think you're lazy. This city invented the concept of 'slow living': a laid-back rhythm, 8,000 teahouses, and a food scene that's officially recognized by UNESCO as a City of Gastronomy.",
    "It's also the gateway to western Sichuan — the mountains, monasteries and gorges that make this one of China's most scenic provinces. But the city itself is the star: giant pandas at dawn, Sichuan opera at dusk, and a hotpot dinner in between that will test your spice tolerance and steal your heart."
  ],
  "top5": [
    {"id":"panda-base", "title":"Giant Panda Breeding Base", "tag":"Watch pandas at their most active — 8am", "ph_emoji":"🐼",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460328/panda_yyeilx.jpg",
     "alt":"Giant panda eating bamboo",
     "story":"Opened in 1987, this 100-hectare research base has grown from six rescued pandas to a population of over 200 — the most successful panda breeding program on earth, and the model for panda conservation worldwide. Red pandas roam the same park, and the base has also released captive pandas successfully into the wild.",
     "why":"Nowhere else gives you this access to giant pandas: you can watch them munch bamboo, climb trees and (in breeding season) cuddle their cubs, just meters away. The 8am feeding time is when they're most active — by 10am most are asleep and the tour buses have arrived.",
     "tip":"Arrive at 7:30am opening and head straight to the Moonlight Nursery to see the cubs. Allow 3 hours. It's 20 minutes by taxi or metro Line 3 (Panda Avenue station) + shuttle. Entry 55 RMB."},
    {"id":"jinli", "title":"Jinli Street &amp; Wuhou Shrine", "tag":"Three Kingdoms history + lantern-lit lanes", "ph_emoji":"🏮",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460323/sichuan-opera_tugsbh.jpg",
     "alt":"Sichuan opera performance",
     "story":"Wuhou Shrine was built in 223 AD to honor Zhuge Liang, the legendary strategist of the Three Kingdoms era, and Liu Bei, the Shu Han emperor — the only temple in China housing both a ruler and his minister. Next door, Jinli Street re-creates the old Shu kingdom's marketplace: lanterns, snack stalls, folk crafts, and nightly Sichuan opera with face-changing performances.",
     "why":"This is the most atmospheric introduction to Sichuan's history and culture in one stop: a 1,800-year-old story told through temples, teahouses and street theater. The face-changing (bianlian) opera performers who swap masks in a blink are a genuine art form you'll see nowhere else.",
     "tip":"Visit Wuhou Shrine in the afternoon (50 RMB), then walk into Jinli as the sun sets — the lanterns make it magical. Catch the opera/face-changing show inside Jinli (from 60 RMB) in the evening."},
    {"id":"hotpot-dinner", "title":"A real Chengdu hotpot dinner", "tag":"The meal you came for", "ph_emoji":"🍲",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460324/hotpot_p0amdn.jpg",
     "alt":"Sichuan hotpot bubbling",
     "story":"Hotpot began as a working-class dish in Chongqing's docks and became Sichuan's culinary religion. The broth is a deep-red cauldron of chili, Sichuan peppercorns and dozens of spices, bubbling over a gas flame while you cook your own meat, vegetables and noodles. The numbing 'ma' of the peppercorn is what makes it addictive — and uniquely Sichuan.",
     "why":"A Chengdu hotpot dinner is not a meal, it's a ceremony: the boiling pot, the dipping sauces, the cold beer, the hours of conversation. It's the definitive way to taste Sichuan food culture — and the spice level is adjustable, so don't be scared.",
     "tip":"Order the 'yuanyang' (鸳鸯) pot — half spicy, half mild — if you're nervous. Go with locals if you can; they'll order the good stuff (tripe, pig brain, lotus root). Book ahead for dinner, especially on weekends."},
    {"id":"peoples-park", "title":"People's Park teahouse", "tag":"Tea, mahjong &amp; the art of doing nothing", "ph_emoji":"🍵",
     "img":"",
     "story":"People's Park has been Chengdu's living room since 1911. Its centerpiece is the Heming Teahouse (鹤鸣茶社), founded in 1923 — one of the oldest teahouses in China — where locals sit for hours over a 15–30 RMB pot of tea, reading, gossiping, playing mahjong and getting ear-cleaned by wandering barbers with silver tools.",
     "why":"This is the real Chengdu lifestyle, preserved in a public park: an entire city that has perfected the art of doing nothing in public. Watch the old men play chess, listen to the tea-water hawkers, get an ear massage — it's the cheapest, most authentic cultural experience in China.",
     "tip":"Pay for your tea (¥15–30, jasmine or green), find a bamboo chair, and stay as long as you like — nobody rushes you. The ear-cleaning service (采耳) is 30–60 RMB and a surreal, wonderful experience. Afternoon is liveliest."},
    {"id":"wide-narrow-alleys", "title":"Wide &amp; Narrow Alleys (Kuanzhai Xiangzi)", "tag":"Old lanes, new chic", "ph_emoji":"🏘",
     "img":"",
     "story":"These three parallel alleys — Kuan (Wide), Zhai (Narrow) and Jing (Well) — preserve the courtyard houses (siheyuan) of Qing-dynasty Chengdu. Restored in 2008, they now mix traditional teahouses and puppet shows with designer shops, craft beer bars and Sichuan snacks, all under the city's best-preserved old roofs.",
     "why":"It's Chengdu in miniature: ancient lanes, modern energy, and a perfect spot to taste the city's snacks in one walk. The side courtyards hide some of Chengdu's loveliest teahouses and courtyard restaurants, far quieter than the main alleys.",
     "tip":"Come in the late afternoon for golden light on the grey-brick lanes, then stay for dinner and drinks. Free entry. Try the 'san da pao' (三大炮) dessert — glutinous rice balls with a theatrical bounce."}
  ],
  "stay": [
    {"name":"Taikoo Li / Chunxi Road", "badge":"Best for first-timers",
     "desc":"Chengdu's fashionable center: the open-air Taikoo Li mall (glass pavilions around a Tang-dynasty temple) and the Chunxi Road shopping street, with metro Lines 2 and 3 crossing here. Most sights are 10–20 minutes by taxi or metro.",
     "metro":"Lines 2/3 · Chunxi Road", "landmark":"Taikoo Li, Daci Temple, Chunxi Road",
     "hotel":"e.g. The Temple House (iconic luxury inside Taikoo Li) · Buddha Zen Hotel (traditional courtyard, great value)"},
    {"name":"Wide &amp; Narrow Alleys", "badge":"Atmosphere &amp; food lovers",
     "desc":"Sleep among the old lanes: courtyard hotels and guesthouses tucked behind the Kuanzhai alley walls, minutes from People's Park's teahouses and the city's best snack streets. Quieter and more charming than the shopping center.",
     "metro":"Lines 2/4 · People's Park", "landmark":"Kuanzhai Xiangzi, People's Park, Wenshu Monastery",
     "hotel":"e.g. Courtyard hotels inside the alleys · Wenshu Monastery-area guesthouses"},
    {"name":"Wenshu Monastery area", "badge":"Budget &amp; local life",
     "desc":"Around the 1,400-year-old Wenshu Monastery, this older quarter has street markets, vegetarian restaurants, and Chengdu's famous Wenshu snack street — plus the cheapest decent hotels in the center. More authentic, less polished.",
     "metro":"Line 1 · Wenshu Monastery", "landmark":"Wenshu Monastery, Wenshu snack street",
     "hotel":"e.g. Lazybones Hostel (backpacker favorite) · budget hotels along the monastery wall"},
    {"name":"South High-tech District", "badge":"Modern &amp; transit-savvy",
     "desc":"The modern business district south of the center: sleek hotels, international restaurants, and a direct metro link (Line 1) to the train stations and airport. Choose this if you prefer comfort and quiet over old-town charm.",
     "metro":"Lines 1 · Century City / Financial City", "landmark":"Global Center (world's largest building), Century City",
     "hotel":"e.g. InterContinental Century City · international chains"}
  ],
  "eat": [
    {"name":"Hotpot (Huoguo)", "zh":"火锅", "ph_emoji":"🍲",
     "img":"",
     "desc":"The bubbling cauldron of chili oil and Sichuan peppercorns — Chengdu's culinary religion. Cook your own meat and veg in the broth, dip in sesame-oil sauce, repeat until happy.",
     "where":"🍽 Shu Daxia (蜀大侠) · Xiaolongkan · ¥80–150 pp · book ahead"},
    {"name":"Dan Dan Noodles", "zh":"担担面", "ph_emoji":"🍜",
     "img":"",
     "desc":"The taste of Chengdu in one bowl: springy noodles in a spicy, numbing, peanut-flecked sauce with minced pork — street food elevated to legend.",
     "where":"🍽 Chengdu snack chains (Long Chao Shou, 龙抄手) · ¥12–18"},
    {"name":"Sweet Water Noodles", "zh":"甜水面", "ph_emoji":"🍜",
     "img":"",
     "desc":"Thick, chewy noodles coated in a sweet-spicy sauce of brown sugar and chili — uniquely Chengdu, and the perfect palate cleanser after the numbing stuff.",
     "where":"🍽 Snack shops in Kuanzhai &amp; Jinli · ¥12–15"},
    {"name":"Mapo Tofu", "zh":"麻婆豆腐", "ph_emoji":"🌶",
     "img":"",
     "desc":"Silken tofu in a fiery, numbing sauce of minced beef and fermented bean paste — named after the pockmarked ('mapo') woman who invented it in 1860s Chengdu. A certified classic.",
     "where":"🍽 Chen Mapo Tofu (陈麻婆豆腐, original since 1862) · ¥30–45"}
  ],
  "tips": [
    "Panda Base opens at 7:30am — be there at opening. Pandas are most active during breakfast and asleep by 10am; the tour buses arrive at 9:30am.",
    "Sichuan's famous 'ma' (麻) numbness comes from the Sichuan peppercorn — embrace it. And learn one word: 'wei-la' (微辣) = mild, your hotpot safety word.",
    "Teahouse etiquette: one pot of tea (15–30 RMB) buys you a seat for hours. People's Park's Heming Teahouse is the classic — arrive after 3pm for the liveliest scene.",
  ],
  "related": [
    {"file":"chongqing.html", "zh":"重庆", "en":"Chongqing", "emoji":"🔥", "desc":"Cyberpunk city, hotpot capital, mountain drama",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460321/hongya-cave_kb6jvj.jpg"},
    {"file":"xian.html", "zh":"西安", "en":"Xi'an", "emoji":"🏺", "desc":"Ancient history, Terracotta Army, Silk Road",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460318/terracotta-army_pp8yhk.jpg"},
  ],
})

# ============================================================ CHONGQING
CITIES.append({
  "file": "chongqing.html",
  "title": "Chongqing Travel Guide — Ready? China!",
  "meta": "The honest guide to Chongqing for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "重庆", "en": "Chongqing", "emoji": "🔥",
  "sub": "Cyberpunk city, hotpot capital, mountain drama",
  "meta_tags": ["★★★☆☆", "🗓 2–3 days", "Unique architecture", "Best hotpot", "Spicy!"],
  "hero_bg": "https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460321/hongya-cave_kb6jvj.jpg",
  "hero_grad": "linear-gradient(135deg, #3a1e1e 0%, #7a3a2a 100%)",
  "why_emoji": "🔥",
  "why": [
    "Chongqing is China's most surreal city — a mega-city of 32 million people built on mountains where two rivers meet, and the trains run through apartment buildings. Photographers call it cyberpunk: buildings stacked on buildings, neon-lit bridges layered over the Yangtze, and an elevator ride that feels like a mountain hike.",
    "It's also the birthplace of Chinese hotpot — the original, dangerously spicy broth — and it's famous for one of China's friendliest street-food scenes. Come for the impossible architecture, stay for the food, and leave wondering how any of it was built."
  ],
  "top5": [
    {"id":"hongya-cave", "title":"Hongya Cave at night", "tag":"The most photographed spot in Chongqing", "ph_emoji":"🏮",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460321/hongya-cave_kb6jvj.jpg",
     "alt":"Hongya Cave stacked buildings lit at night",
     "story":"Hongya Cave ('Red Cliff Cave') is an 11-story complex of traditional stilted houses built into the cliff above the Jialing River, completed in 2006. Its stacked wooden pavilions — styled after the old riverside dwellings that once filled Chongqing — light up at night into a glowing, multi-tiered pagoda-like structure that everyone compares to the movie Spirited Away.",
     "why":"At night it's pure magic: golden lanterns, balconies full of teahouses and snack shops, and the Jialing River reflecting the whole glowing stack below. It's the definitive Chongqing photo — and inside, the fourth-floor food street is a full local snack market.",
     "tip":"Come after 7pm when it's fully lit. The classic view is from across the river on the Hongya Cave side; from the Jiefangbei side walk down to the riverfront for the postcard shot. Free entry, busy on weekends."},
    {"id":"jiefangbei", "title":"Jiefangbei &amp; the CBD", "tag":"The city's beating heart", "ph_emoji":"🏙",
     "img":"",
     "story":"Jiefangbei ('Liberation Monument') is a 27.5-meter obelisk built in 1947 to mark victory in the War of Resistance, standing in the middle of Chongqing's busiest shopping district. Around it, the CBD mixes brand malls, street markets, and the city's famous '8D' pedestrian network of elevated walkways and underground passages.",
     "why":"This is Chongqing's downtown — the place to feel the city's relentless energy, shop, and watch the crowds. Just steps away you'll find the Ronghui and Shibati old streets climbing the hillside, and the best rooftop bars with skyline views.",
     "tip":"Stand at the monument at sunset, then follow the downhill stair-streets toward the river — the walk down Jiefangbei's hillside alleys is a mini-adventure in itself. Free."},
    {"id":"hotpot", "title":"Original Chongqing hotpot", "tag":"The spiciest broth on earth", "ph_emoji":"🍲",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460321/hotpot_gsk4di.jpg",
     "alt":"Chongqing hotpot",
     "story":"Chongqing hotpot was born in the 1920s when dock workers boiled cheap beef offal in a shared pot of spiced broth on the riverside. From that pot grew a culinary empire: today the city has over 30,000 hotpot restaurants, and the local saying goes 'a good hotpot is 80% oil' — a churning, blood-red cauldron of chili, peppercorn and butter that's the spiciest in China.",
     "why":"This isn't just a meal, it's the city's identity — and it's genuinely different from the Sichuan hotpot next door: heavier, oilier, fiercer. Order the classic 'jiuge' (nine-grid) pot to divide your ingredients, and brace yourself for the legendary 'wei' (numbing) that follows.",
     "tip":"Get the yuanyang (鸳鸯) half-mild pot if you're not a veteran. Locals swear by dipping everything in sesame oil (it cuts the spice). Top spots: Qiuzui Hotpot, Xiao Longkan — ¥80–150 pp."},
    {"id":"liziba", "title":"Liziba — the train through a building", "tag":"A metro line runs right through an apartment block", "ph_emoji":"🚈",
     "img":"",
     "story":"At Liziba station, Chongqing's Line 2 monorail passes directly through the 19th floor of an ordinary apartment building. The station and the building were designed together in 2004 — the residents get soundproofing, and the train gets one of the world's most famous commuter routes, gliding out of a wall over the Jialing River.",
     "why":"It's the purest example of Chongqing's impossible architecture — a city where a train is your upstairs neighbor. Watch from the observation platform below as the monorail disappears into the building, and ride the line yourself for the river-and-cliff views.",
     "tip":"Take Line 2 and ride a couple of stops — the river crossing is beautiful. The best photo spot is the plaza across the street from Liziba station. Free; metro ride ~3 RMB."},
    {"id":"ciqikou", "title":"Ciqikou Ancient Town", "tag":"A thousand-year-old porcelain town", "ph_emoji":"🏘",
     "img":"",
     "story":"Ciqikou ('Porcelain Port') is a hilltop town that has stood above the Jialing River for over 1,000 years, thriving as a porcelain-making and shipping port since the Ming dynasty. Its stone lanes, teahouses and riverside cliff paths survived the 20th century largely intact, and it's now Chongqing's best-preserved old town.",
     "why":"It's a glimpse of the river-trade Chongqing that existed before the skyscrapers: Ming-style gateways, Sichuan opera stages, teahouses on the cliff edge, and the best place in the city to shop for handmade porcelain and watch calligraphers work.",
     "tip":"Go on a weekday morning before the tour groups. Walk downhill to the river for the old ferry view, then climb back up for lunch at one of the cliffside teahouses. Free entry."}
  ],
  "stay": [
    {"name":"Jiefangbei CBD", "badge":"Best for first-timers",
     "desc":"Chongqing's center: the Liberation Monument, shopping, the metro hub and Hongya Cave are all within walking distance (or a 10-minute taxi). Everything on your list is 15–30 minutes away by metro or taxi.",
     "metro":"Lines 1/2/6 · Xiaoshizi / Jiefangbei", "landmark":"Jiefangbei, Hongya Cave, Yangtze cable car",
     "hotel":"e.g. Niccolo Chongqing (sky-high luxury in IFS Tower) · JI Hotel (great value near Jiefangbei)"},
    {"name":"Nanbin Road (South Bank)", "badge":"Skyline views",
     "desc":"Across the Yangtze, the Nanbin Road waterfront looks directly at the downtown skyline — the best night views in the city, plus riverside restaurants and bars. Slightly less convenient, considerably more romantic.",
     "metro":"Line 6/环线 · Nanbin Road", "landmark":"Yangtze cable car, Danzishi old street",
     "hotel":"e.g. Chongqing Marriott (river-view rooms) · mid-range riverside hotels"},
    {"name":"Guanyinqiao", "badge":"Foodies &amp; shoppers",
     "desc":"Chongqing's second downtown and unofficial food capital: the Guanyinqiao night market and the surrounding streets hold some of the city's best hotpot and snacks, with direct metro access to the center in 15 minutes.",
     "metro":"Lines 3/9 · Guanyinqiao", "landmark":"Guanyinqiao night market, 9 Streets food alley",
     "hotel":"e.g. Holiday Inn Express · local chains (very good value)"},
    {"name":"Ciqikou area", "badge":"Old-town atmosphere",
     "desc":"Stay near the ancient town for riverside teahouses and cliff paths in the morning before the crowds. It's a 30–40 minute metro ride to the CBD, but you wake up in old Chongqing.",
     "metro":"Line 1 · Ciqikou", "landmark":"Ciqikou old town, Jialing River",
     "hotel":"e.g. boutique guesthouses near the old town gate"}
  ],
  "eat": [
    {"name":"Chongqing Hotpot", "zh":"重庆火锅", "ph_emoji":"🍲",
     "img":"",
     "desc":"The original — a churning cauldron of chili oil and peppercorns born on the docks. Fiercer, oilier and more addictive than anywhere else on earth.",
     "where":"🍽 Qiuzui Hotpot (秋咀) · Xiao Longkan · ¥80–150 pp"},
    {"name":"Xiaomian (little noodles)", "zh":"小面", "ph_emoji":"🍜",
     "img":"",
     "desc":"Chongqing's street breakfast: simple noodles in chili oil, vinegar and crushed peanuts — deceptively plain, devastatingly good. The city's answer to 'how to start the day'.",
     "where":"🍽 Any xiaomian shop with a queue · ¥8–15"},
    {"name":"Suanlafen", "zh":"酸辣粉", "ph_emoji":"🌶",
     "img":"",
     "desc":"Hot and sour glass noodles with peanuts, pickled vegetables and chili — street food perfection, usually eaten standing up from a paper bowl.",
     "where":"🍽 Jiefangbei &amp; Ciqikou street stalls · ¥10–15"},
    {"name":"Maoxuewang", "zh":"毛血旺", "ph_emoji":"🥘",
     "img":"",
     "desc":"A fiery Sichuan-Chongqing classic: duck blood, tripe and vegetables swimming in a vast bowl of chili and peppercorn oil. Adventurous, and unforgettable.",
     "where":"🍽 Sichuan restaurants citywide · ¥60–100"}
  ],
  "tips": [
    "Chongqing is built on mountains — you WILL get lost. Google Maps doesn't work well here; use Amap (高德) or Baidu Maps, and remember that 'two blocks away' might mean a 20-story climb.",
    "The Yangtze River cable car (2 RMB) across the river is a working commuter line, not a tourist ride — do it at sunset for the best skyline approach.",
    "Order hotpot with 'weila' (微辣) if you're not a spice veteran, and always get the sesame-oil dip — it's not optional, it's survival.",
  ],
  "related": [
    {"file":"chengdu.html", "zh":"成都", "en":"Chengdu", "emoji":"🐼", "desc":"Pandas, hotpot, chill vibes, authentic local life",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460328/panda_yyeilx.jpg"},
    {"file":"guilin.html", "zh":"桂林", "en":"Guilin", "emoji":"🏔️", "desc":"Nature, karst mountains, Li River scenery",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460324/li-river_lpbtrp.jpg"},
  ],
})

# ============================================================ GUILIN
CITIES.append({
  "file": "guilin.html",
  "title": "Guilin Travel Guide — Ready? China!",
  "meta": "The honest guide to Guilin for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "桂林", "en": "Guilin", "emoji": "🏔️",
  "sub": "Nature, karst mountains, Li River scenery",
  "meta_tags": ["★★☆☆☆", "🗓 3–4 days", "Jaw-dropping views", "Outdoor adventure"],
  "hero_bg": "https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460324/li-river_lpbtrp.jpg",
  "hero_grad": "linear-gradient(135deg, #2a4a3a 0%, #5a8a6a 100%)",
  "why_emoji": "🏔️",
  "why": [
    "Guilin's limestone peaks are the image of China that lives in everyone's head — those misty, impossibly pointy mountains rising out of green rice fields and rivers, printed on the 20 RMB note. For 2,000 years Chinese painters have been trying to capture this landscape; you just have to stand in it.",
    "The best part is how easy it is: cruise the Li River, bike through Yangshuo's countryside, hike the Longji rice terraces — all of it is an hour or two from Guilin city. It's the perfect 'nature fix' for travelers coming from Beijing or Shanghai's urban intensity."
  ],
  "top5": [
    {"id":"li-river-cruise", "title":"Li River cruise to Yangshuo", "tag":"The most beautiful river journey in China", "ph_emoji":"⛵",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460324/li-river_lpbtrp.jpg",
     "alt":"Li River karst mountains",
     "story":"The Li River winds 83 km from Guilin to Yangshuo through the karst landscape that inspired Chinese painters for centuries — and that appears on the back of the 20 RMB banknote. The classic 4–5 hour cruise takes you past hundreds of sheer limestone peaks, bamboo groves and water buffalo, on a river that's been called the most beautiful in China since Tang-dynasty poets said so.",
     "why":"This is the single most iconic landscape in China — the mountains-and-mist scene you've seen in a thousand paintings, in person. The cruise is comfortable (you sit inside with a viewing deck), and the scenery changes with every bend: peaks named after their shapes, fishing villages, and the famous 'Nine Horses' cliff.",
     "tip":"Book the cruise from Guilin (from ~360 RMB, includes transport to the dock). Bring snacks and binoculars. In the off-season the river can be shallow — check the water level before you book; the alternative is a bamboo raft from Yangdi."},
    {"id":"yangshuo-countryside", "title":"Yangshuo countryside by bike", "tag":"Rice paddies, karst peaks &amp; zero crowds", "ph_emoji":"🚲",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460326/yu-long-rafting_kuxreh.jpg",
     "alt":"Bamboo rafting on Yulong River, Yangshuo",
     "story":"South of Yangshuo town, the Yulong River threads through the most beautiful countryside in China: rice paddies, lotus ponds, ancient bridges and villages tucked under the karst peaks. This is the landscape the cruise passes at a distance — up close, on a rented bike or bamboo raft, it becomes personal.",
     "why":"Cycling the Yulong River valley is the classic Yangshuo experience: flat, quiet roads, farmers working the fields, and a karst peak around every corner. Add a bamboo raft (2–4 people, 30–60 minutes) on the Yulong and you've done the postcard scene properly — with hardly a tourist in sight.",
     "tip":"Rent an e-bike or regular bike in Yangshuo (~30–60 RMB/day) and ride the Yulong River loop from the town to the Gongnong Bridge. Start before 9am for the morning mist. Bamboo rafts ~100–160 RMB per raft."},
    {"id":"elephant-trunk-hill", "title":"Elephant Trunk Hill", "tag":"Guilin's postcard landmark", "ph_emoji":"🐘",
     "img":"",
     "story":"A limestone hill shaped so perfectly like an elephant drinking from the river that it's been Guilin's symbol since the Tang dynasty — the 'trunk' forms a natural arch called Water Moon Cave. It sits at the meeting point of the Li and Taohua rivers, right in the city, and appears on Guilin's skyline logo.",
     "why":"It's the one sight in Guilin that looks exactly like the postcard — a giant stone elephant kneeling at the water's edge. The park around it is small and easy, and the riverside walk from here into the old town is one of the city's most pleasant strolls.",
     "tip":"Entry 55 RMB; go in the late afternoon for golden light on the 'elephant'. Free alternative: view it from the riverside promenade on the opposite bank (Zhengyang Road side) — same photo, no ticket."},
    {"id":"reed-flute-cave", "title":"Reed Flute Cave", "tag":"A fairy-tale cave of colored lights", "ph_emoji":"🕳",
     "img":"",
     "story":"Named after the reeds growing at its entrance that locals once used to make flutes, Reed Flute Cave is a 240-meter-long limestone grotto packed with stalactites, stalagmites and underground lakes. It was opened to visitors in 1962, and its formations — lit in theatrical colors — have hosted visiting heads of state ever since, including Mao-era diplomacy.",
     "why":"It's one of China's most spectacular caves: a full underground landscape of 'frozen waterfalls', crystal pillars and mirror-still lakes, illuminated like a stage set. The 60-minute walk-through is a cool, dry, perfectly easy way to spend an afternoon.",
     "tip":"Entry 100 RMB. Go right at opening (8am) to beat the tour groups. The reflections on the underground lake are the photo to get. It's 6 km from the center — taxi or bus 3."},
    {"id":"longji-terraces", "title":"Longji Rice Terraces", "tag":"2,000-year-old stairs to the sky", "ph_emoji":"🌾",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460327/longji-rice-terraces_wxtjnl.jpg",
     "alt":"Longji rice terraces",
     "story":"In the hills of Longsheng County, the Zhuang and Yao people have carved rice terraces into the mountainsides for over 700 years — a staircase of green that climbs from valley to cloud level. The two main viewpoints, Ping'an and Jinkeng (Dazhai), offer the classic panorama: tier after tier of flooded paddies catching the light, with Yao women in red jackets selling handicrafts at the top.",
     "why":"This is one of the great man-made landscapes of China — a full mountain transformed by generations of farmers. It's at its most spectacular in May (the water-filling season, when the terraces become mirrors) and October (the golden harvest), and the hike between viewpoints is a proper mountain adventure.",
     "tip":"Longji is 2 hours from Guilin — take a bus from Guilin Bus Station or a day tour (~200–300 RMB). Stay overnight in a farmstay at Ping'an for sunrise over the terraces; the light is worth the early alarm."}
  ],
  "stay": [
    {"name":"Guilin city center (Xiangshan)", "badge":"Best base &amp; transit",
     "desc":"Guilin's old center around Elephant Trunk Hill and the Zhengyang pedestrian street: hotels for every budget, the Two Rivers and Four Lakes night cruise departs from here, and the Li River cruise dock and train station are both close. Best choice if you're arriving/leaving by train or plane.",
     "metro":"No metro — taxis and buses; Guilin North Station 20 min by taxi", "landmark":"Elephant Trunk Hill, Zhengyang Road, Two Rivers &amp; Four Lakes",
     "hotel":"e.g. Guilin Central Hotel · Shangri-La Guilin (river views, splurge)"},
    {"name":"Yangshuo old town", "badge":"Scenery &amp; nightlife",
     "desc":"The best base for countryside days: West Street's restaurants and bars, the Yulong River bike loops, and karst peaks out your window. It's 1.5 hours from Guilin city by bus or car — choose it if scenery beats convenience.",
     "metro":"No metro — shuttle bus or taxi from Guilin (1.5h)", "landmark":"West Street, Yulong River, Moon Hill",
     "hotel":"e.g. Banyan Tree Yangshuo (iconic luxury) · Yangshuo Mountain Retreat (eco-lodge on Yulong River)"},
    {"name":"Yulong River valley", "badge":"Peace &amp; nature immersion",
     "desc":"Farmstays and boutique hotels along the Yulong River, surrounded by rice paddies and peaks — the quietest, most beautiful place to sleep in the region. You'll need a bike or scooter to get around, which is half the fun.",
     "metro":"No metro — bike or scooter; 15 min from Yangshuo town", "landmark":"Yulong River, Gongnong Bridge, Jiuxian village",
     "hotel":"e.g. Yangshuo Mountain Retreat · riverside farmstays from ¥300"},
    {"name":"Longji terraces (Longsheng)", "badge":"Terraces &amp; sunrise",
     "desc":"Farmstays on the terrace viewpoints themselves — wooden guesthouses with views over the steps to the sky. The whole point is the sunrise; you'll trade comfort (basic rooms, shared facilities at budget places) for one of China's best views.",
     "metro":"No metro — 2h from Guilin by bus", "landmark":"Ping'an &amp; Jinkeng viewpoints, Yao villages",
     "hotel":"e.g. farmstays at Ping'an (from ¥200) · Longji International Youth Hostel (budget)"}
  ],
  "eat": [
    {"name":"Guilin Rice Noodles", "zh":"桂林米粉", "ph_emoji":"🍜",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782635742/guilin-rice-noodle_czaxkw.jpg",
     "alt":"Bowl of Guilin rice noodles",
     "desc":"The breakfast of champions: slippery rice noodles in a rich bone broth (or dry-tossed), topped with pickled beans, chili, peanuts and fresh herbs. Cheap, fast, and exactly right.",
     "where":"🍽 Any local fen shop — follow the morning queue · ¥10–15"},
    {"name":"Beer Fish", "zh":"啤酒鱼", "ph_emoji":"🐟",
     "img":"",
     "desc":"Li River fish braised in beer and tomatoes until the sauce is glossy and sweet-sour — the signature dish of Yangshuo, best eaten at a riverside table.",
     "where":"🍽 Yangshuo West Street &amp; Yulong River restaurants · ¥60–100 per fish"},
    {"name":"Luosifen", "zh":"螺蛳粉", "ph_emoji":"🍜",
     "img":"",
     "desc":"River snail noodles in a pungent, sour-spicy broth with pickled bamboo shoots — the most polarizing dish in China, and utterly addictive once you're in. It's Luosifen's home region, so this is the real thing.",
     "where":"🍽 Snail noodle shops in Guilin &amp; Yangshuo · ¥12–20"},
    {"name":"Oil Tea", "zh":"油茶", "ph_emoji":"🍵",
     "img":"",
     "desc":"A savory tea brewed with ginger, garlic and pounded tea leaves, poured over popped rice and peanuts — a Yao and Zhuang mountain tradition that's the perfect pick-me-up after a Longji hike.",
     "where":"🍽 Longji villages &amp; Guilin teahouses · ¥10–20"}
  ],
  "tips": [
    "The Li River cruise is the classic, but check water levels in winter — if the river is low, swap to the bamboo raft from Yangdi to Xingping (the 20 RMB note view).",
    "Yangshuo's countryside is best at 7–9am, before the tour groups: rent an e-bike and ride the Yulong River loop with the mist still on the water.",
    "Longji's terraces are magical in May (flooded mirrors) and October (golden harvest) — and the Yao women at the top sell excellent handicrafts, so bring cash.",
  ],
  "related": [
    {"file":"chongqing.html", "zh":"重庆", "en":"Chongqing", "emoji":"🔥", "desc":"Cyberpunk city, hotpot capital, mountain drama",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460321/hongya-cave_kb6jvj.jpg"},
    {"file":"hangzhou.html", "zh":"杭州", "en":"Hangzhou", "emoji":"🌊", "desc":"Serenity, West Lake, tea culture, easy day trips",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460323/west-lake_dslidh.jpg"},
  ],
})

# ============================================================ HANGZHOU
CITIES.append({
  "file": "hangzhou.html",
  "title": "Hangzhou Travel Guide — Ready? China!",
  "meta": "The honest guide to Hangzhou for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "杭州", "en": "Hangzhou", "emoji": "🌊",
  "sub": "Serenity, West Lake, tea culture, easy day trips",
  "meta_tags": ["★☆☆☆☆", "🗓 2–3 days", "Beautiful & calm", "Near Shanghai"],
  "hero_bg": "https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460323/west-lake_dslidh.jpg",
  "hero_grad": "linear-gradient(135deg, #1e3c4a 0%, #3a6b7a 100%)",
  "why_emoji": "🌊",
  "why": [
    "Hangzhou is the city Chinese poets have been praising for a thousand years — Marco Polo called it 'the finest and most splendid city in the world'. The centerpiece is West Lake, a 6-square-km lake of temples, pagodas and willow-lined causeways that's been a UNESCO World Heritage Site since 2011 and the model for 'Chinese paradise' in countless paintings.",
    "It's also the home of Longjing (Dragon Well) tea, China's most famous green tea, and it's just 45 minutes from Shanghai by high-speed train — which makes it the easiest beautiful-day-trip in China, and a perfect 2–3 day escape from the big-city pace."
  ],
  "top5": [
    {"id":"west-lake", "title":"West Lake by bike &amp; boat", "tag":"The classic Chinese landscape, in person", "ph_emoji":"⛵",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460323/west-lake_dslidh.jpg",
     "alt":"West Lake with pagoda",
     "story":"West Lake has been China's favorite landscape since the Tang dynasty, when poets and emperors shaped it into a garden of causeways, islands and pagodas — including the Bai and Su causeways, the Three Pools Mirroring the Moon, and Leifeng Pagoda on the south shore. It became a UNESCO World Heritage Site in 2011 as 'a masterpiece of landscape design that has influenced garden art across East Asia'.",
     "why":"You can circle the whole lake (about 15 km) by shared bike in an afternoon, or take a wooden boat to the islands — either way you're inside the landscape that defined how China pictures paradise. The sunrise over Broken Bridge and the sunset from Su Causeway are the two classic moments.",
     "tip":"Rent a shared bike (~1.5 RMB/30 min) or join a boat from the shore (¥50–150 for a private rowing boat). Go early — the lake at 7am with morning mist is the version the paintings are based on."},
    {"id":"lingyin-temple", "title":"Lingyin Temple &amp; Feilai Feng", "tag":"A 1,600-year-old mountain monastery", "ph_emoji":"🛕",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460319/lingyin-temple_ja3zuc.jpg",
     "alt":"Lingyin Temple",
     "story":"Lingyin ('Soul's Retreat') Temple was founded in 326 AD by an Indian monk, making it one of China's oldest and most important Buddhist temples. It sits beneath Feilai Feng ('Peak That Flew Here'), a limestone crag studded with over 300 carved Buddha statues from the Five Dynasties and Song period — some over 1,000 years old — including the famous laughing Maitreya carved in 951 AD.",
     "why":"It's the full Chinese temple experience in one hillside: incense smoke, chanting, centuries-old carvings in the cliffs, and the largest hall of its kind in China with a 24.8-meter wooden Buddha. The Feilai Feng grottoes are the artistic highlight — ancient sculpture in a forest setting.",
     "tip":"Entry is 45 RMB (Feilai Feng) + 30 RMB (temple) — buy both. Go before 9am to beat the crowds. Budget 2–3 hours. The vegetarian restaurant inside the temple complex is excellent."},
    {"id":"longjing-tea-village", "title":"Longjing Tea Village", "tag":"Pick, roast &amp; drink China's most famous tea", "ph_emoji":"🍃",
     "img":"",
     "story":"Longjing (Dragon Well) is China's most celebrated green tea, and this hillside village — set among the terraced plantations of West Lake's south shore — is where it all began, with over 1,200 years of tea history. In spring (especially March–April), visitors can pick leaves in the terraces, watch master roasters fry them by hand in woks (the traditional '10 techniques'), and taste the first flush of the year.",
     "why":"There's no more complete tea experience in China: the fields, the craft, and the taste of tea that emperors once reserved for themselves. The village teahouses serve fresh Longjing with spring water, and the terraced hills are gorgeous even outside harvest season.",
     "tip":"Visit in late March to mid-April for picking season (pick-your-own experiences from ~100 RMB). Genuine 'Shifeng' Longjing is pricey (¥2,000+/kg for top grade); buy from a registered farmhouse, not the roadside sellers."},
    {"id":"hefang-street", "title":"Hefang Street &amp; Qinghefang", "tag":"The old city's food &amp; crafts street", "ph_emoji":"🏮",
     "img":"",
     "story":"Hefang ('Royal Street') and its continuation Qinghefang sit on the site of the Southern Song dynasty's imperial street, when Hangzhou was the capital of China (1127–1279). The restored pedestrian street is packed with traditional shops: silk, tea, medicine halls like the 140-year-old Hu Qingyutang pharmacy, and enough snack stalls to eat your way down the whole block.",
     "why":"This is Hangzhou's old city in one walk — Southern Song history, crafts you can watch being made (paper-cutting, silk embroidery), and the city's densest snack street. It's also where the 2,000-year-old 'dragon-well tea ceremony' shops and the famous Quyuan Fenghe lotus area begin.",
     "tip":"Go at 6pm when the lanterns come on. Try the 'ding sheng gao' (定胜糕) steamed cakes and the sweet-osmanthus lotus root. Free entry; the Hu Qingyutang pharmacy museum is worth 30 minutes."},
    {"id":"leifeng-pagoda", "title":"Leifeng Pagoda at sunset", "tag":"The tower of the White Snake legend", "ph_emoji":"🗼",
     "img":"",
     "story":"The original pagoda was built in 975 AD by the King of Wuyue — and immortalized in China's most famous love story, the Legend of the White Snake, in which a spirit is imprisoned beneath it. The tower collapsed in 1924, and the current pagoda (rebuilt 2002) stands on the ruins, which are preserved under glass so you can see the original foundations and a buried Buddha relic.",
     "why":"The sunset view from Leifeng Pagoda's top floor is the classic Hangzhou photo: the whole of West Lake laid out below, with the city glowing behind the mountains. And the story attached to it — part fairy tale, part archaeology — makes it the most atmospheric of the lake's landmarks.",
     "tip":"Entry 40 RMB, open until 8pm. Time your climb for 30 minutes before sunset. The elevator goes up (yes, there's an elevator in a 975 AD pagoda), so it's accessible to everyone."}
  ],
  "stay": [
    {"name":"Hugbin / Lake East shore", "badge":"Best for first-timers",
     "desc":"The east shore of West Lake, facing the water: step out and you're on the lakefront promenade, with the metro, the old city and the shopping streets behind you. The classic Hangzhou base — walkable to almost everything.",
     "metro":"Line 1 · Longxiangqiao / Fengqi Road", "landmark":"West Lake, Broken Bridge, Hefang Street",
     "hotel":"e.g. Four Seasons Hangzhou (lakefront luxury) · Midtown Shangri-La (landmark, lake views)"},
    {"name":"Yanggong Causeway / Lingyin area", "badge":"Peace &amp; nature",
     "desc":"The west and northwest shores are quieter and greener — hidden villas, teahouses and bamboo paths, 10 minutes from Lingyin Temple. Perfect for couples and anyone who wants the lake without the crowds.",
     "metro":"No metro — taxi or bus to the lake edge (15 min)", "landmark":"Lingyin Temple, Su Causeway, bamboo groves",
     "hotel":"e.g. Amanfayun (ultra-luxury in a tea village) · Mejiawu farmstay tea houses"},
    {"name":"Qinghefang / Southern Song area", "badge":"Old-city atmosphere",
     "desc":"The historic south: Hefang Street's food and crafts at your door, the canal old town, and the lake a 10-minute walk north. The most atmospheric budget-to-mid option, with the best street food nearby.",
     "metro":"Line 1 · Ding'an Road", "landmark":"Hefang Street, Hu Qingyutang, Wushan Hill",
     "hotel":"e.g. boutique guesthouses on the old streets · West Lake Youth House (budget, friendly)"},
    {"name":"Qianjiang New City (east)", "badge":"Modern &amp; convenient",
     "desc":"Hangzhou's modern CBD along the Qiantang River: business hotels, the tide-viewing riverfront, and metro access to the lake in 20 minutes. Choose it for hotel quality and value over old-city charm.",
     "metro":"Lines 2/4 · Qianjiang Road", "landmark":"Qiantang River, Hangzhou Grand Theatre, tide bore",
     "hotel":"e.g. JW Marriott Hangzhou · InterContinental Hangzhou (landmark tower)"}
  ],
  "eat": [
    {"name":"Dongpo Pork", "zh":"东坡肉", "ph_emoji":"🍖",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460313/dongpo-pork_wajz0k.jpg",
     "alt":"Braised dongpo pork",
     "desc":"Melt-in-your-mouth braised pork belly, slow-cooked in soy, sugar and wine until it's glossy and tender — named after the Song-dynasty poet Su Dongpo, who served it while governing Hangzhou.",
     "where":"🍽 Lou Wai Lou (楼外楼, famous since 1848, lake view) · ¥50–80"},
    {"name":"Longjing Shrimp", "zh":"龙井虾仁", "ph_emoji":"🦐",
     "img":"",
     "desc":"Freshwater shrimp stir-fried with young Longjing tea leaves — delicate, fragrant and uniquely Hangzhou. The tea's slight bitterness against the sweet shrimp is the whole point.",
     "where":"🍽 Lou Wai Lou · Guohao Hotel restaurant · ¥80–120"},
    {"name":"West Lake Vinegar Fish", "zh":"西湖醋鱼", "ph_emoji":"🐟",
     "img":"",
     "desc":"Grass carp in a sweet-sour vinegar sauce with a hint of ginger — a Hangzhou classic that's an acquired taste (the fish is cooked whole, bones and all), but a must-try.",
     "where":"🍽 Lou Wai Lou · ¥80–100"},
    {"name":"Beggar's Chicken", "zh":"叫花鸡", "ph_emoji":"🍗",
     "img":"",
     "desc":"A whole chicken stuffed with mushrooms and ham, wrapped in lotus leaves and baked in clay — cracked open at the table with a mallet. Smoky, juicy and theatrical.",
     "where":"🍽 Hangzhou classic restaurants (Lou Wai Lou, Grandma's Home) · ¥60–90"}
  ],
  "tips": [
    "Hangzhou is 45 minutes from Shanghai by high-speed rail (¥73) — perfect for a day trip, but stay overnight for the lake at sunrise and the teahouse afternoon.",
    "West Lake is free to walk; only the islands, temples and pagodas charge. The sunrise walk from Broken Bridge to Su Causeway is the best free show in China.",
    "March–April is tea-picking season AND the lake's prettiest weather — but also China's peak travel season, so book hotels a month ahead.",
  ],
  "related": [
    {"file":"shanghai.html", "zh":"上海", "en":"Shanghai", "emoji":"🌃", "desc":"Futuristic skyline, international food, modernity",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460304/bund_vqnbql.jpg"},
    {"file":"guilin.html", "zh":"桂林", "en":"Guilin", "emoji":"🏔️", "desc":"Nature, karst mountains, Li River scenery",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460324/li-river_lpbtrp.jpg"},
  ],
})

# ============================================================ QUANZHOU
CITIES.append({
  "file": "quanzhou.html",
  "title": "Quanzhou Travel Guide — Ready? China!",
  "meta": "The honest guide to Quanzhou for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "泉州", "en": "Quanzhou", "emoji": "🌸",
  "sub": "Hidden gem, Maritime Silk Road, authentic local China",
  "meta_tags": ["★★★★☆", "🗓 2–3 days", "K's hometown! 🏠", "UNESCO 2021", "Off the beaten path"],
  "hero_bg": "https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460308/kaiyuan-temple_sgbmat.jpg",
  "hero_grad": "linear-gradient(135deg, #4a2a3a 0%, #7a4a6a 100%)",
  "why_emoji": "🌸",
  "why": [
    "Quanzhou is the hidden gem of China's coast — a port that was one of the world's greatest cities a thousand years ago, when Arab, Persian, Indian and European traders anchored in its harbor on the Maritime Silk Road. In 2021, UNESCO added the whole historic city to the World Heritage list, and yet almost no foreign tourists come. That's your gain.",
    "It's also Kat's hometown — so this guide comes with a local's heart. You'll find China's oldest mosque, a 1,300-year-old Buddhist temple, temples where Hindu deities and Mazu (the sea goddess) share walls, and food that blends Fujian, Southeast Asian and Arab influences into something you can't get anywhere else. Come before the world discovers it."
  ],
  "top5": [
    {"id":"kaiyuan-temple", "title":"Kaiyuan Temple &amp; the Twin Pagodas", "tag":"1,300 years of Buddhist history", "ph_emoji":"🛕",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460308/kaiyuan-temple_sgbmat.jpg",
     "alt":"Kaiyuan Temple pagodas",
     "story":"Founded in 686 AD during the Tang dynasty, Kaiyuan Temple is one of the largest and oldest Buddhist temples in China — its two stone pagodas, the 44.06-meter East Pagoda and 43.85-meter West Pagoda, have stood since the 13th century and are the tallest stone pagodas in China. The temple's pillars carry carvings of Hindu deities and music-loving angels, proof of Quanzhou's cosmopolitan past.",
     "why":"This is the heart of Quanzhou — a huge, living temple where locals still burn incense among 1,300-year-old banyan trees. The twin pagodas are the city's symbol (they appear in old sailors' charts as landmarks for approaching ships), and the temple grounds are a peaceful green oasis in the old city.",
     "tip":"Free entry. Go early (opens 6:30am) to see the morning prayers, then explore the surrounding Xijie (West Street) for old-town atmosphere and snacks. The Hindu-carved pillars are on the right side of the main hall — don't miss them."},
    {"id":"zhongshan-road", "title":"Zhongshan Road", "tag":"Southern China's most beautiful old street", "ph_emoji":"🏘",
     "img":"",
     "story":"Zhongshan Road is a 2.5-km arcade-lined street that has been Quanzhou's commercial spine since the 1920s, built on top of the old city's Tang-dynasty street grid. Its covered walkways (qilou) — a Fujian and Southeast Asian architectural style — sheltered merchants from sun and rain, and the street remains the most beautiful pedestrian route in southern China.",
     "why":"This is where Quanzhou's everyday life happens: teahouses, shops selling tea and incense, old medicine halls, and families on scooters dodging between the columns. Unlike polished tourist streets elsewhere, this one is genuinely lived-in — and at night, when the awnings light up, it's stunning.",
     "tip":"Walk it at dusk (around 7pm) when the lanterns come on. Branch into the side lanes — Zhongshan Road's alleys hide courtyards, temples and the city's best cheap eats."},
    {"id":"maritime-museum", "title":"Maritime Silk Road Museum", "tag":"The story of China's greatest port", "ph_emoji":"⚓",
     "img":"",
     "story":"Quanzhou's Maritime Silk Road Museum tells the story of the city that was, for centuries, one of the world's busiest ports — where Marco Polo sailed from in 1292 and Ibn Battuta visited in 1346. The museum's centerpiece is a 13th-century Song-dynasty ship, 24 meters long, raised from Quanzhou Bay in 1974 — the oldest Chinese trading vessel ever recovered, with 2,300 artifacts found on board.",
     "why":"No other museum in China tells the Maritime Silk Road story so completely: the ship, the cargo, the religious stone carvings (Christian, Islamic, Hindu, Manichaean — all found in Quanzhou), and the city's unique role as a meeting point of world religions. It explains why Quanzhou matters more than almost any other Chinese city.",
     "tip":"Free entry, open Tue–Sun 9am–5pm (closed Mondays). Allow 1.5–2 hours. The Song ship in the main hall is the unmissable object; the stone-carving gallery is the second must-see."},
    {"id":"qingjing-mosque", "title":"Qingjing Mosque", "tag":"China's oldest surviving mosque", "ph_emoji":"🕌",
     "img":"",
     "story":"Built in 1009 AD during the Northern Song dynasty, Qingjing Mosque is the oldest surviving mosque in China — founded by Arab traders who made Quanzhou their home. Its grey stone arches and courtyard carry Arabic inscriptions, and the site remained a place of worship into the Ming dynasty, when it was visited and repaired with support from the Chinese court.",
     "why":"It's a physical trace of the cosmopolitan world that made Quanzhou rich: a thousand years ago, this city had mosques, temples and churches standing side by side, and people of every faith traded together. Standing in the mosque's quiet courtyard, you're in one of the most important religious sites in China — and almost nobody else is there.",
     "tip":"Entry 3 RMB. Modest dress expected. It's a 10-minute walk from Kaiyuan Temple — combine the two in one morning. The adjacent Peace Street (Tumen Street) has the best local snacks."},
    {"id":"guandi-temple", "title":"Guandi Temple (Guan Yue Temple)", "tag":"The busiest temple in the old city", "ph_emoji":"🏮",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460310/guandi-temple_qrt1ax.jpg",
     "alt":"Guandi Temple Quanzhou",
     "story":"This temple honors Guan Yu, the deified general of the Three Kingdoms era who became China's god of loyalty and business — and Quanzhou's Guandi Temple is among the busiest in the country. Local businesspeople still come daily to burn incense and ask for fortune, shaking numbered bamboo sticks until one falls, then reading their answer from a drawer of poems.",
     "why":"This is Quanzhou's everyday religion, in action: a temple where the incense smoke never stops and where you'll see more genuine worship in five minutes than in a week of tourist temples elsewhere. You can even try the fortune-telling ritual yourself — a unique, immersive local experience.",
     "tip":"Free entry. Learn the fortune-stick ritual (you can watch others first) — if you get a 'bad' fortune, it's customary to tie it to the tree outside. Go on the 1st or 15th of the lunar month for the fullest scene."}
  ],
  "stay": [
    {"name":"West Street / Kaiyuan Temple area", "badge":"Best for first-timers",
     "desc":"The old city's historic heart: Kaiyuan Temple and the twin pagodas at one end of West Street, Zhongshan Road and the snack alleys at the other. Guesthouses in restored Minnan courtyard houses give you old-town atmosphere with everything walkable.",
     "metro":"No metro — walk, bike or taxi (small city, 5–15 min rides)", "landmark":"Kaiyuan Temple, West Street, Zhongshan Road",
     "hotel":"e.g. Wutong House (boutique B&amp;B in a restored house) · Quanzhou Guesthouse International"},
    {"name":"Zhongshan Road / Tumen Street", "badge":"Foodies &amp; night owls",
     "desc":"The old commercial spine: stay above the arcades and you're in the middle of the snack streets, the night market and the Guandi Temple's incense. Quieter than West Street's tourist edge, more authentic.",
     "metro":"No metro — everything within walking distance", "landmark":"Zhongshan Road, Guandi Temple, Qingjing Mosque",
     "hotel":"e.g. courtyard guesthouses off Tumen Street · budget hotels on Zhongshan"},
    {"name":"Donghai / coast area", "badge":"Modern &amp; beach escape",
     "desc":"The newer east side near Quanzhou Bay: business hotels, the Maritime Silk Road Museum, and easy access to the coast's fishing villages and seafood restaurants. Choose it if you want modern comfort or plan a day at the bay.",
     "metro":"No metro — 15 min taxi to old city", "landmark":"Maritime Silk Road Museum, Quanzhou Bay, beaches",
     "hotel":"e.g. Quanzhou Bay Hotel · international business chains"},
    {"name":"Jinjiang (south bank)", "badge":"Business &amp; connections",
     "desc":"Across the river, the city of Jinjiang is where many of Quanzhou's factories and the airport are — a practical base if you're mixing business with tourism, 25 minutes from the old city by car.",
     "metro":"No metro — taxi/bus to Quanzhou old city (25 min)", "landmark":"Jinjiang airport, Wu Dian Shi old street",
     "hotel":"e.g. Marco Polo Hotel Jinjiang (business landmark)"}
  ],
  "eat": [
    {"name":"Oyster Omelette", "zh":"蚵仔煎", "ph_emoji":"🦪",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460305/minnan-oyster-pancake_a9hfl1.jpg",
     "alt":"Minnan oyster omelette",
     "desc":"Crispy-edged, gooey-centered: fresh oysters bound with sweet-potato starch and egg, fried until the edges are lacy — the ultimate Minnan street food, served with a sweet chili dip.",
     "where":"🍽 West Street &amp; Tumen Street stalls · ¥15–25"},
    {"name":"Satay Noodles", "zh":"沙茶面", "ph_emoji":"🍜",
     "img":"",
     "desc":"Quanzhou's signature comfort food: wheat noodles in a rich, savory broth of satay sauce, peanut and seafood — a taste left by the city's centuries of maritime trade. Add your choice of fish balls, squid or pork.",
     "where":"🍽 Local noodle shops across the old city · ¥15–30"},
    {"name":"Runbing (fresh spring rolls)", "zh":"润饼", "ph_emoji":"🌯",
     "img":"",
     "desc":"Paper-thin crepes rolled around a sweet-savory filling of shredded vegetables, peanuts, sugar and sometimes seafood — sweet, crunchy, soft and salty all at once.",
     "where":"🍽 Tumen Street &amp; temple-side vendors · ¥8–15"},
    {"name":"Seaweed &amp; seafood soup", "zh":"紫菜海蛎汤", "ph_emoji":"🍲",
     "img":"",
     "desc":"A clear, briny soup of local seaweed and small oysters — the taste of the Fujian coast, light and restorative after a day of temple-hopping.",
     "where":"🍽 Seafood restaurants near West Street · ¥20–40"}
  ],
  "tips": [
    "Quanzhou is 1 hour from Xiamen by high-speed train — pair them: Xiamen's island charm + Quanzhou's authenticity. Kat's tip: do Quanzhou first, Xiamen second, so you end on the beach.",
    "Almost no English is spoken — download Pleco and a translation app before you come. It's part of the charm: you're visiting a city that hasn't been 'discovered' yet.",
    "The best snack street is Tumen Street (涂门街) near the Guandi Temple, and the best time is 7–9pm. Try everything; the oyster omelette and satay noodles are non-negotiable.",
  ],
  "related": [
    {"file":"xian.html", "zh":"西安", "en":"Xi'an", "emoji":"🏺", "desc":"Ancient history, Terracotta Army, Silk Road",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460318/terracotta-army_pp8yhk.jpg"},
    {"file":"hangzhou.html", "zh":"杭州", "en":"Hangzhou", "emoji":"🌊", "desc":"Serenity, West Lake, tea culture, easy day trips",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460323/west-lake_dslidh.jpg"},
  ],
})

# ============================================================ DUNHUANG
CITIES.append({
  "file": "dunhuang.html",
  "title": "Dunhuang Travel Guide — Ready? China!",
  "meta": "The honest guide to Dunhuang for first-time visitors: why go, top 5 must-sees with real history, where to stay by district, and what to eat.",
  "zh": "敦煌", "en": "Dunhuang", "emoji": "🕌",
  "sub": "Silk Road art, Mogao Caves, desert landscapes",
  "meta_tags": ["★★★☆☆", "🗓 3–4 days", "UNESCO caves", "Silk Road", "Desert"],
  "hero_bg": "",
  "hero_grad": "linear-gradient(135deg, #7a5a2a 0%, #c9a05a 100%)",
  "why_emoji": "🕌",
  "why": [
    "Dunhuang is the place where the Silk Road met the desert — a remote oasis town that for over 1,500 years was the gateway where China, Central Asia and India exchanged goods, faiths and art. Its Mogao Caves hold the greatest collection of Buddhist art on earth: 45,000 square meters of murals painted across a thousand years, hidden in a cliff for centuries and now a UNESCO World Heritage Site.",
    "Then there's the desert itself: singing sand dunes, a crescent-shaped lake that never dries up, camel caravans at sunset, and a night sky so clear you can see the Milky Way. Dunhuang is far, but it's the most unforgettable 'wow' stop on any China itinerary."
  ],
  "top5": [
    {"id":"mogao-caves", "title":"Mogao Caves", "tag":"The greatest Buddhist art on earth", "ph_emoji":"🕌",
     "img":"",
     "story":"In 366 AD, a monk named Le Zun saw a golden vision on a cliff above the Dachuan River and carved the first cave shrine there. Over the next 1,000 years, 735 caves were cut into the cliff, decorated with 45,000 square meters of murals and 2,400 painted sculptures — a Silk Road masterpiece mixing Chinese, Indian, Persian and Greek influences. A UNESCO World Heritage Site since 1987, it's known as the 'Louvre of the Desert'.",
     "why":"The murals are simply overwhelming: flying apsaras (heavenly dancers), thousand-armed Bodhisattvas, and the story of Buddhism's journey across Asia painted in colors that still glow after 1,400 years. Only a small number of caves are open to the public each day, which keeps it intimate — and the experience of standing in a 1,000-year-old cave is unlike anything else in China.",
     "tip":"Book tickets at least 2 weeks ahead (they sell out — daily limit is 6,000). Entry from 238 RMB includes a 30-minute documentary and a guided tour of ~8 caves. Bring a small flashlight for the darker caves; photography is forbidden inside (they enforce it)."},
    {"id":"mingsha-dunes", "title":"Mingsha Mountain &amp; Crescent Moon Spring", "tag":"Singing sand dunes &amp; a desert lake", "ph_emoji":"🏜️",
     "img":"",
     "story":"Mingsha ('Singing Sand') Mountain is a range of dunes that 'sing' — when the wind moves the sand or you slide down the slopes, it hums like an orchestra. At its foot lies Crescent Moon Spring, a 2,000-year-old lake that has never dried up despite being surrounded by desert, its water fed by underground springs and protected from the sand by the dune's shape.",
     "why":"It's the full desert experience done properly: camel rides through the dunes, sandboarding (or sledding) down the singing slopes, and the surreal sight of a lake surviving in the middle of a desert. At sunset, the dunes turn gold and the camel caravans make the scene look straight out of a movie.",
     "tip":"Go at 5pm — the sand has cooled, the light is golden, and the sunset over the dunes is the photo you want. Entrance 110 RMB; camel ride ~100 RMB for 1 hour. Climb the dune to the left of the entrance for the classic crescent-lake view."},
    {"id":"yumen-pass", "title":"Yumen Pass &amp; the Great Wall's western end", "tag":"Where the Silk Road left China", "ph_emoji":"🏛️",
     "img":"",
     "story":"Yumen ('Jade Gate') Pass was built in 111 BC by Emperor Wu of the Han dynasty as the western gateway of China — the last checkpoint where Silk Road caravans said goodbye to home before the desert crossing to Central Asia. A stretch of the Han Great Wall (the oldest kind, built of compacted sand and reeds) still stands nearby, and the poet Wang Zhihuan's line 'beyond the Jade Gate the spring wind never blows' made it famous across China.",
     "why":"Standing at Yumen Pass, you're at the edge of the empire — the same gate through which Zhang Qian, Marco Polo-era merchants and centuries of traders passed. The loneliness of the desert all around makes it one of the most atmospheric historical sites in China, and the crumbling Han-era wall nearby is astonishingly old.",
     "tip":"Yumen Pass is 90 km northwest of Dunhuang — take a taxi or join the west-line day tour (also covers the Great Wall and the Yadan 'Ghost City' rock formations, ¥300–400 total). Carry water — there is nothing out there."},
    {"id":"shazhou-night-market", "title":"Shazhou Night Market", "tag":"Dunhuang's desert bazaar after dark", "ph_emoji":"🏮",
     "img":"",
     "story":"When the sun goes down, Dunhuang's streets fill with smoke and music: the Shazhou Night Market is the town's evening heart, serving lamb skewers, hand-pulled noodles, apricot-water drinks and desert-grown melons, alongside stalls of sand-painted art, camel-bone carvings and Silk Road handicrafts.",
     "why":"After a day of caves and dunes, this is where Dunhuang relaxes — a bazaar that feels straight off the Silk Road, with the town's best food and its friendliest atmosphere. The grilled lamb and the local apricot-flavored drinks are the standouts.",
     "tip":"Go at 8pm when it's fully alive. Try the 'xingpishui' (杏皮水) apricot drink and the skewers from the stalls with the longest queues. Bargaining is expected on handicrafts — start at half the asking price."},
    {"id":"camel-sunset", "title":"Sunset camel ride over the dunes", "tag":"The classic Silk Road photo", "ph_emoji":"🐫",
     "img":"",
     "story":"For over 2,000 years, camels were the trucks of the Silk Road — and in Dunhuang they're still the best way into the dunes. The desert sunset camel trek climbs the singing sand at golden hour, when the dunes shift from gold to rose to purple and the shadows stretch across the sand like water.",
     "why":"It's the single most iconic Silk Road image — a camel caravan crossing the dunes at sunset — and you can be in it. The silence of the desert at dusk, broken only by the camels' bells and the 'singing' sand, is one of those moments that stays with you for years.",
     "tip":"The 1-hour camel loop in Mingsha Mountain park is ~100 RMB; go at 5:30–6pm for sunset. Dress warmly — desert nights drop fast, even in summer. For a truly remote version, book the longer camel trek into the dunes (~2 hours, from the far entrance)."}
  ],
  "stay": [
    {"name":"Dunhuang city center", "badge":"Best base &amp; night market",
     "desc":"The compact city center puts you walking distance from the Shazhou Night Market, the museum and the morning bus stops for the west-line tours. Everything in Dunhuang is small — from here you're 10 minutes from the dunes and 25 from the Mogao Caves by taxi.",
     "metro":"No metro — taxis are cheap (~5–20 RMB across town)", "landmark":"Shazhou Night Market, Dunhuang Museum, Baimata Pagoda",
     "hotel":"e.g. Silk Road Dunhuang Hotel (traditional decor) · Shazhou Hotel (mid-range, walkable to market)"},
    {"name":"Mingsha Mountain edge", "badge":"Desert &amp; sunrise",
     "desc":"Guesthouses along the road to the dunes let you walk to Mingsha in minutes — perfect for sunrise over the sand, the one moment the dunes are empty. A 15-minute taxi to the center when you need the city.",
     "metro":"No metro — taxi to center ~15 RMB", "landmark":"Mingsha Mountain, Crescent Moon Spring",
     "hotel":"e.g. desert-side guesthouses &amp; glamping tents (Mingsha area)"},
    {"name":"Mogao Caves area", "badge":"Culture immersion",
     "desc":"A handful of quiet guesthouses sit near the caves' entrance, surrounded by orchards and desert — the place to stay if you want to be first through the gates at 8:30am and last out. Rustic, but unforgettable evenings under desert stars.",
     "metro":"No metro — taxi to town 25 min", "landmark":"Mogao Caves, Shazhou Old Town",
     "hotel":"e.g. farmstay guesthouses near the cave entrance"},
    {"name":"Dunhuang Old Town (west)", "badge":"Budget &amp; authentic",
     "desc":"The older quarter west of the center: cheaper hotels, local restaurants, and the atmosphere of a real Gansu desert town rather than the tourist strip. 10 minutes by taxi from everything.",
     "metro":"No metro — walk or taxi", "landmark":"Dunhuang Old Town streets, local markets",
     "hotel":"e.g. budget hotels &amp; hostels in the old town"}
  ],
  "eat": [
    {"name":"Lanzhou Beef Noodles", "zh":"兰州牛肉面", "ph_emoji":"🍜",
     "img":"",
     "desc":"Hand-pulled noodles in a rich, clear beef broth with chili oil and cilantro — Gansu's soul food, served everywhere in Dunhuang. The 'one clear, two white, three red, four green' bowl: clear soup, white radish, red chili, green herbs.",
     "where":"🍽 Any beef noodle shop with a queue · ¥12–20"},
    {"name":"Liangpi (cold noodles)", "zh":"酿皮子", "ph_emoji":"🥗",
     "img":"",
     "desc":"Chilled wheat or rice noodles in sesame paste and chili oil with cucumber and gluten cubes — refreshing in the desert heat, and a Dunhuang street staple.",
     "where":"🍽 Night market &amp; street stalls · ¥10–15"},
    {"name":"Lamb Skewers", "zh":"羊肉串", "ph_emoji":"🍢",
     "img":"",
     "desc":"Charcoal-grilled lamb dusted with cumin and chili, eaten with cold beer under the night-market smoke — the taste of the desert after dark.",
     "where":"🍽 Shazhou Night Market · ¥3–5 per skewer"},
    {"name":"Apricot Water", "zh":"杏皮水", "ph_emoji":"🥤",
     "img":"",
     "desc":"Dunhuang's signature drink: dried local apricots simmered into a sweet-sour amber cooler, served iced. The perfect desert antidote — sweet, tangy and deeply local.",
     "where":"🍽 Night market stalls · ¥5–10 per cup"}
  ],
  "tips": [
    "Book Mogao Caves tickets 2+ weeks in advance online — the daily quota is tight and the English tour is excellent. Go in the first time slot (8:30am) for the quietest caves.",
    "Dunhuang is best April–June and September–October. Summer is scorching (40°C+ on the sand) — if you must come in July–August, do dunes at 5pm and caves in the morning.",
    "The west-line day tour (Yumen Pass + Han Great Wall + Yadan 'Ghost City') is worth every yuan — book it through your hotel the night before, and carry water and a hat.",
  ],
  "related": [
    {"file":"xian.html", "zh":"西安", "en":"Xi'an", "emoji":"🏺", "desc":"Ancient history, Terracotta Army, Silk Road",
     "img":"https://res.cloudinary.com/dosiqd0h4/image/upload/v1782460318/terracotta-army_pp8yhk.jpg"},
    {"file":"kashgar.html", "zh":"喀什古城", "en":"Kashgar", "emoji":"🏛️", "desc":"Uyghur craft bazaar, Silk Road living museum",
     "grad":"background:linear-gradient(135deg,#7a5a2a,#c9a05a)"},
  ],
})
